add chapter 24
aivivn/Machine-Learning-Yearning-Vietnamese-Translation pull request #192
Opened 2019-10-29 05:00 UTC by seanphan

## Nếu bạn tạo Pull Request để dịch, vui lòng hoàn thành các thông tin dưới đây.

* [x] Đánh dấu [x] (không có dấu cách quanh x) thể hiện dấu tick vào các câu dưới đây cho các câu trả lời 'Có' hoặc 'Đúng'

* [x] Pull Request này được link tới một issue? Đánh số issue đó *ngay sau* dấu #187 

* [x] Bạn có kiến thức về Machine Learning không? Chúng tôi ưu tiên những người có trước kiến thức về Machine Learning để việc review được thuận tiện hơn.

* [x] Bạn đã đọc [Bảng thuật ngữ](https://github.com/aivivn/Machine-Learning-Yearning-Vietnamese-Translation/blob/master/glossary.md) chưa? Bạn cần dịch các thuật ngữ theo bảng thuật ngữ chung.

* [x] Tất cả các thuật ngữ trong chương này đã có trong [Bảng thuật ngữ](https://github.com/aivivn/Machine-Learning-Yearning-Vietnamese-Translation/blob/master/glossary.md) chưa? Nếu chưa, bạn có thể tạo một issue hoặc pull request mới để bổ sung nghĩa của từ đó vào Bảng thuật ngữ.

* [x] Pull request này đã sẵn sàng cho việc review chưa? Nếu đã sẵn sàng, bạn vui lòng gán label 'review wanted' cho pull request này. Nếu chưa, bạn vui lòng thêm cụm "[WIP]" (work in progress) vào trước tiêu đề của pull request.

## Lưu ý 
**Chỉ bắt đầu review khi mọi mục trên đây đều đã được tick.**

2019-10-31 15:49 UTC, phamdinhkhanh commented
Em xin review chương này nha anh Tiệp.

2019-10-31 16:30 UTC, tiepvupsu commented
> Em xin review chương này nha anh Tiệp.

Review thì cứ làm thôi, không cần đăng ký đâu em :D @phamdinhkhanh

2019-11-01 06:29 UTC, tiepvupsu requested changes

2019-11-01 06:29 UTC, tiepvupsu commented on chapters/ch24.md
> +Bạn có thể đã nghe nói về "Sự đánh đổi giữa Độ chệch và Phuơng sai". Trong số các thay đổi bạn có thể thực hiện đối với hầu hết các thuật toán learning, có một số cách giảm lỗi Độ chệch nhưng với chi
Đề xuất:
> ... có một số cách giảm lỗi Độ chệch nhưng ~~với chi phí gia~~ _đổi lại khiến_ tăng Phuơng sai và ngược lại...

2019-11-01 06:29 UTC, tiepvupsu commented on chapters/ch24.md
> +Ví dụ việc tăng kích thước mô hình của bạn, thêm các nơ-ron / lớp trong mạng neural hoặc thêm các đặc trưng đầu vào, nhìn chung sẽ làm giảm Độ chệch nhưng có thể làm tăng Phương sai. Ngoài ra, việc t
* "layer" -> "tầng"
* Dấu "-" trong bản gốc nên được giữ nguyên vì đoạn giữa hai dấu "-" thể hiện việc giải thích cho ý trước đó. Nhân tiện, chỗ này cần dùng hai dấu "--". Bản tiếng Anh do copy nên bị lỗi format.
* Không có dấu cách quanh dấu "/"
* Ở đây "bias" và "variance" không viết hoa, tiếng Việt cũng tương tự.
* "Alternatively" mang nghĩa là "Ngược lại" hay "Một cách làm khác". Chỗ này mình chưa biết dịch thế nào cho sát.

2019-11-01 06:29 UTC, tiepvupsu commented on chapters/ch24.md
> +Trong thời kỳ hiện đại, chúng ta thường có quyền truy cập vào dữ liệu phong phú và có thể sử dụng các mạng lưới neural rất lớn (deep learning). Do đó, có ít sự đánh đổi hơn, và hiện có nhiều lựa chọn
* không có chữ "lưới" sau "mạng"
* Tương tự không viết hoa "độ chệch" và "phương sai" ở đây và những chỗ phía dưới.

2019-11-01 06:29 UTC, tiepvupsu commented on chapters/ch24.md
> +Trong một vài chương tiếp theo, chúng ta sẽ thảo luận về các kỹ thuật cụ thể bổ sung để giải quyết Độ chệch và Phương sai.
bỏ từ "bổ sung"

2019-11-01 07:15 UTC, phamdinhkhanh requested changes
@seanphan xem các nội dung anh đã review nhé. Cần cập nhật lại:
* Các điều chỉnh trên file gốc.
* Push update lên current branch.

2019-11-01 07:15 UTC, phamdinhkhanh commented on chapters/ch24.md
> +#24. Sự đánh đổi giữa Độ chệch và Phuơng sai
**Format chỉnh sửa**
* Các từ bị thay thế trong bản gốc bị gạch ngang.
* Các từ thêm mới trong bản gốc được in nghiêng.

**Lưu ý**
* Các điều chỉnh sẽ không thay đổi file. Bạn cần đọc lại review, sau đó cập nhật lại file và push lên branch git của bạn.

Bắt đầu review tại đây

#24. Sự đánh đổi giữa Độ chệch và <s>Phuơng</s> _Phương_ sai

2019-11-01 07:15 UTC, phamdinhkhanh commented on chapters/ch24.md
> +Bạn có thể đã nghe nói về "Sự đánh đổi giữa Độ chệch và Phuơng sai". Trong số các thay đổi bạn có thể thực hiện đối với hầu hết các thuật toán learning, có một số cách giảm lỗi Độ chệch nhưng với chi
Bạn có thể đã nghe nói về "Sự đánh đổi giữa Độ chệch và <s>Phuơng</s> _Phương_ sai" trong <s>số</s> các thay đổi <s>có thể thực hiện</s> _được thực hiện_ <s>đối với</s> trên hầu hết các thuật toán <s>learning</s>_học máy_, có một số cách giảm <s>lỗi</s> _sai số_ Độ chệch nhưng <s>với chi phí gia tăng</s> với _chi phí phải trả_ là gia tăng <s>Phuơng</s> _Phương_ sai và ngược lại. Điều này tạo ra một sự "đánh đổi" giữa Độ chệch và Phương sai.

**Note:**
Thêm các thuật ngữ "Bias" --> "Độ chệch", "Bias error" --> "Sai số chệch", "Bias vs. Variance tradeoff." --> "Đánh đổi giữa độ chệch và phương sai" vào glossary.md

2019-11-01 07:15 UTC, phamdinhkhanh commented on chapters/ch24.md
> +Ví dụ việc tăng kích thước mô hình của bạn, thêm các nơ-ron / lớp trong mạng neural hoặc thêm các đặc trưng đầu vào, nhìn chung sẽ làm giảm Độ chệch nhưng có thể làm tăng Phương sai. Ngoài ra, việc t
Ví dụ, việc tăng kích thước mô hình của bạn _bằng cách_ thêm các nơ-ron / lớp trong mạng neural hoặc thêm các _đầu vào_ đặc trưng _tổng quát_ <s>đặc trưng</s> sẽ làm giảm Độ chệch nhưng có thể làm tăng Phương sai. Ngoài ra, việc thêm <s>regularization</s> _thành phần kiểm soát_ thường làm tăng Độ chệch nhưng giảm Phương sai.

Note:
Thêm ý nghĩa cho thuật ngữ "regularization" là "thành phần kiểm soát".

2019-11-01 07:15 UTC, phamdinhkhanh commented on chapters/ch24.md
> +Trong thời kỳ hiện đại, chúng ta thường có quyền truy cập vào dữ liệu phong phú và có thể sử dụng các mạng lưới neural rất lớn (deep learning). Do đó, có ít sự đánh đổi hơn, và hiện có nhiều lựa chọn
<s>Trong thời kỳ hiện đại</s> _Ngày nay_, chúng ta thường <s>có quyền</s> truy cập vào _nhiều nguồn_ dữ liệu <s>phong phú</s> và có thể sử dụng các mạng <s>lưới</s> neural rất lớn (<s>deep learning</s> _trong lĩnh vực học sâu_). Do đó, có ít <s>sự</s> đánh đổi hơn, và hiện _tại_ có nhiều lựa chọn hơn để giảm Độ chệch mà không làm ảnh hưởng Phương sai, và ngược lại.

2019-11-01 07:15 UTC, phamdinhkhanh commented on chapters/ch24.md
> +Ví dụ: bạn thường có thể tăng kích thước mạng neural và điều chỉnh phương thức regularization để giảm Độ chệch mà không làm tăng đáng kể Phương sai. Bằng cách thêm dữ liệu huấn luyện, bạn cũng có thể
Ví dụ: bạn <s>thường</s> có thể tăng kích thước mạng neural và điều chỉnh phương thức <s>regularization</s> _kiểm soát_ để giảm Độ chệch mà không <s>làm</s> _gia_ tăng đáng kể <s>Phương</s> _Phương_ sai. Bằng cách thêm dữ liệu huấn luyện, bạn cũng có thể <s>thường xuyên</s> giảm Phương sai mà không ảnh hưởng đến Độ chệch.

2019-11-01 07:15 UTC, phamdinhkhanh commented on chapters/ch24.md
> +Nếu bạn chọn một kiến ​​trúc mô hình phù hợp với tác vụ của mình, bạn cũng có thể giảm đồng thời Độ chệch và Phương sai. Tuy nhiên sẽ khó khăn để chọn một kiến ​​trúc như vậy.
Nếu <s>bạn</s> chọn một kiến ​​trúc mô hình _rất_ phù hợp với tác vụ của mình, bạn <s>cũng</s> có thể giảm đồng thời Độ chệch và Phương sai. Tuy nhiên sẽ khó khăn để chọn một kiến ​​trúc như vậy.

Note:
Thêm "task" --> "tác vụ" vào glossary.md.

2019-11-01 07:15 UTC, phamdinhkhanh commented on chapters/ch24.md
> +Trong một vài chương tiếp theo, chúng ta sẽ thảo luận về các kỹ thuật cụ thể bổ sung để giải quyết Độ chệch và Phương sai.
Trong một vài chương tiếp theo, chúng ta sẽ thảo luận <s>về</s> các kỹ thuật <s>cụ thể</s> bổ sung _cụ thể_ để giải quyết Độ chệch và Phương sai.

2019-11-01 16:59 UTC, sonvx commented on chapters/ch24.md
> +Ví dụ việc tăng kích thước mô hình của bạn, thêm các nơ-ron / lớp trong mạng neural hoặc thêm các đặc trưng đầu vào, nhìn chung sẽ làm giảm Độ chệch nhưng có thể làm tăng Phương sai. Ngoài ra, việc t
*Neurons* mình vẫn chưa thống nhất cách dịch và các chương trước vẫn để nguyên. Nên bạn cũng để nguyên *neurons* nhé. Để sau cần replace thì sẽ thay thế đồng nhất.

2019-11-01 17:01 UTC, sonvx commented on chapters/ch24.md
> +Ví dụ việc tăng kích thước mô hình của bạn, thêm các nơ-ron / lớp trong mạng neural hoặc thêm các đặc trưng đầu vào, nhìn chung sẽ làm giảm Độ chệch nhưng có thể làm tăng Phương sai. Ngoài ra, việc t
*Neurons* mình vẫn chưa thống nhất cách dịch và các chương trước vẫn để nguyên. Nên bạn cũng để nguyên *neurons* nhé. Để sau cần replace thì sẽ thay thế đồng nhất.

2019-11-02 04:21 UTC, seanphan commented
Ok @phamdinhkhanh @tiepvupsu , mình sẽ update trong hôm nay nhé

2019-11-02 06:43 UTC, seanphan commented on chapters/ch24.md
> +Ví dụ việc tăng kích thước mô hình của bạn, thêm các nơ-ron / lớp trong mạng neural hoặc thêm các đặc trưng đầu vào, nhìn chung sẽ làm giảm Độ chệch nhưng có thể làm tăng Phương sai. Ngoài ra, việc t
Mình đã fix hết mấy point trên nha. Khúc "Alternatively" mình để thành "Một cách khác" cũng tương tự như bạn gợi ý.

2019-11-02 06:45 UTC, seanphan commented on chapters/ch24.md
> +Trong một vài chương tiếp theo, chúng ta sẽ thảo luận về các kỹ thuật cụ thể bổ sung để giải quyết Độ chệch và Phương sai.
Do trong bản gốc có chữ "additionally" nên mình để thêm chữ bổ sung. Hiện tại mình rephase đoạn này thành: "Trong một vài chương tiếp theo, chúng ta sẽ thảo luận thêm về các kỹ thuật cụ thể để giải quyết Độ chệch và Phương sai."

2019-11-02 06:52 UTC, seanphan commented on chapters/ch24.md
> +Bạn có thể đã nghe nói về "Sự đánh đổi giữa Độ chệch và Phuơng sai". Trong số các thay đổi bạn có thể thực hiện đối với hầu hết các thuật toán learning, có một số cách giảm lỗi Độ chệch nhưng với chi
Mình đã chỉnh các feedback của bạn trừ khúc  ~~có thể thực hiện~~ *được thực hiện* để giữ nguyên gốc là "you *could* make to most learning algorithms". Về chữ learning, hiện tại mình chưa thống nhất nên mình vẫn giữ lại.

2019-11-02 06:55 UTC, seanphan commented on chapters/ch24.md
> +Ví dụ việc tăng kích thước mô hình của bạn, thêm các nơ-ron / lớp trong mạng neural hoặc thêm các đặc trưng đầu vào, nhìn chung sẽ làm giảm Độ chệch nhưng có thể làm tăng Phương sai. Ngoài ra, việc t
Mình đã update feedback của 2 bạn nha. Riêng *regularization* hiện tại trong glossary đang chưa có dịch nên mình vẫn giữ lại như cũ.

2019-11-02 06:58 UTC, seanphan commented on chapters/ch24.md
> +Ví dụ: bạn thường có thể tăng kích thước mạng neural và điều chỉnh phương thức regularization để giảm Độ chệch mà không làm tăng đáng kể Phương sai. Bằng cách thêm dữ liệu huấn luyện, bạn cũng có thể
Mình giữ chữ *thường* đầu tiên để match với "usually" của tác giả. Phần *regularization* tương tự bên trên. Ngoài ra mình đã update những feedback khác nhé.

2019-11-02 06:59 UTC, seanphan commented on chapters/ch24.md
> +Trong một vài chương tiếp theo, chúng ta sẽ thảo luận về các kỹ thuật cụ thể bổ sung để giải quyết Độ chệch và Phương sai.
Mình update thành "Trong một vài chương tiếp theo, chúng ta sẽ thảo luận thêm các kỹ thuật cụ thể để giải quyết Độ chệch và Phương sai."

2019-11-02 07:02 UTC, seanphan commented on chapters/ch24.md
> +Trong thời kỳ hiện đại, chúng ta thường có quyền truy cập vào dữ liệu phong phú và có thể sử dụng các mạng lưới neural rất lớn (deep learning). Do đó, có ít sự đánh đổi hơn, và hiện có nhiều lựa chọn
Mình đã fix những phần khác và giữ lại chữ deep learning do chưa thống nhất thuật ngữ nha.

2019-11-02 07:04 UTC, seanphan commented on chapters/ch24.md
> +Nếu bạn chọn một kiến ​​trúc mô hình phù hợp với tác vụ của mình, bạn cũng có thể giảm đồng thời Độ chệch và Phương sai. Tuy nhiên sẽ khó khăn để chọn một kiến ​​trúc như vậy.
Mình thêm chữ *rất* để nhấn và giữ lại chữ *bạn* và *cũng* để fit với bản gốc nha.

2019-11-03 04:00 UTC, tiepvupsu commented
Cảm ơn @seanphan, mình có điều chỉnh một chút trước khi approve và merge.

2019-11-03 04:00 UTC, tiepvupsu approved these changes

2019-11-03 04:00 UTC, merged

2019-11-03 04:07 UTC, ngcthuong reviewed
Mình thấy bản này khá OK rồi với Phase 1.
Bạn xem thêm comment nhé

2019-11-03 04:07 UTC, ngcthuong commented on chapters/ch24.md
> +Ngày nay, chúng ta thường có thể truy cập vào nguồn dữ liệu phong phú và có thể sử dụng các mạng neural rất lớn (deep learning). Do đó, có ít đánh đổi hơn, và hiện có nhiều lựa chọn hơn để giảm Độ ch
Mình chưa nghĩ ra từ gì dich cho từ "tradeoff" và không biết có nên viết thêm cho rõ ý đánh đổi ở đây là ý gì không.

- "Phương sai" không viết hoa

2019-11-03 04:07 UTC, ngcthuong commented on chapters/ch24.md
>  Ví dụ: bạn thường có thể tăng kích thước mạng neural và điều chỉnh phương thức regularization để giảm Độ chệch mà không gia tăng đáng kể Phương sai. Bằng cách thêm dữ liệu huấn luyện, bạn cũng thường
- "Phương sai" không viết hoa
- mỉnh chưa rõ lý do bạn viết hoa chữ cái đầu từ khoá Phương sai và Độ chệch
-

2019-11-03 04:07 UTC, ngcthuong commented on chapters/ch24.md
> +Nếu bạn chọn một kiến ​​trúc mô hình rất phù hợp với tác vụ của mình, bạn cũng có thể giảm đồng thời Độ chệch và Phương sai. Tuy nhiên sẽ khó khăn để chọn một kiến ​​trúc như vậy.
Gợi ý câu cuối

"Tuy nhiên,  rất khó để chọn được một kiến trúc như vậy"

2019-11-03 04:07 UTC, ngcthuong commented on chapters/ch24.md
> +Bạn có thể đã nghe nói về "sự đánh đổi giữa Độ chệch và Phương sai". Trong các thay đổi bạn có thể thực hiện đối với hầu hết các thuật toán học, có một số cách giảm sai số độ chệch nhưng với chi phí
- "chi phí" --> giá

2019-11-03 05:00 UTC, tiepvupsu commented on chapters/ch24.md
> +Bạn có thể đã nghe nói về "sự đánh đổi giữa Độ chệch và Phương sai". Trong các thay đổi bạn có thể thực hiện đối với hầu hết các thuật toán học, có một số cách giảm sai số độ chệch nhưng với chi phí
@ngcthuong PR này được merge rồi cậu ạ. Có thể ngay trong lúc cậu đang review.