add chapter 26 and update glossary fỏ background noise
aivivn/Machine-Learning-Yearning-Vietnamese-Translation pull request #193
Opened 2019-10-29 05:19 UTC by seanphan

## Nếu bạn tạo Pull Request để dịch, vui lòng hoàn thành các thông tin dưới đây.

* [x] Đánh dấu [x] (không có dấu cách quanh x) thể hiện dấu tick vào các câu dưới đây cho các câu trả lời 'Có' hoặc 'Đúng'

* [x] Pull Request này được link tới một issue? Đánh số issue đó *ngay sau* dấu #188 

* [x] Bạn có kiến thức về Machine Learning không? Chúng tôi ưu tiên những người có trước kiến thức về Machine Learning để việc review được thuận tiện hơn.

* [x] Bạn đã đọc [Bảng thuật ngữ](https://github.com/aivivn/Machine-Learning-Yearning-Vietnamese-Translation/blob/master/glossary.md) chưa? Bạn cần dịch các thuật ngữ theo bảng thuật ngữ chung.

* [x] Tất cả các thuật ngữ trong chương này đã có trong [Bảng thuật ngữ](https://github.com/aivivn/Machine-Learning-Yearning-Vietnamese-Translation/blob/master/glossary.md) chưa? Nếu chưa, bạn có thể tạo một issue hoặc pull request mới để bổ sung nghĩa của từ đó vào Bảng thuật ngữ.

* [x] Pull request này đã sẵn sàng cho việc review chưa? Nếu đã sẵn sàng, bạn vui lòng gán label 'review wanted' cho pull request này. Nếu chưa, bạn vui lòng thêm cụm "[WIP]" (work in progress) vào trước tiêu đề của pull request.

## Lưu ý 
**Chỉ bắt đầu review khi mọi mục trên đây đều đã được tick.**

2019-10-29 05:28 UTC, william-vu commented
ở chap 22 mình cũng gặp từ background noise & mượn tạp cách dịch của google là "tạp âm". Trong bản dịch chap này mình thấy bạn dịch là "nhiễu nền". Nếu mọi người ok với cách dịch là "nhiễu nền" thì mình update chương của mình.

2019-10-29 06:22 UTC, seanphan commented
Uh lúc đầu mình cũng tính lấy chữ tạp âm mà sau thấy nhiễu nền có vẻ gần với gốc hơn nên pick cách dịch này @william-vu

2019-10-29 08:04 UTC, tiepvupsu commented
Chữ "nhiễu nền" đã được sử dụng ở nhiều nơi.

@seanphan mình sẽ cập nhật từ này vào glossary qua một PR khác để không phải chờ đến khi cả PR lớn này được merge.

2019-10-30 02:16 UTC, seanphan commented
Mình đã resolve conflict nhé

2019-11-01 06:59 UTC, aivivn requested changes

2019-11-01 06:59 UTC, aivivn commented on chapters/ch26.md
> +Thuật toán của bạn phải hoạt động tốt trên tập huấn luyện trước khi bạn có thể mong đợi nó hoạt động tốt trên tập phát triển / kiểm tra.
không có dấu cách quanh '/'.

2019-11-01 06:59 UTC, aivivn commented on chapters/ch26.md
> +Ví dụ: giả sử bạn đang xây dựng một hệ thống nhận dạng giọng nói cho một ứng dụng và đã thu thập một tập huấn luyện gồm các đoạn âm thanh từ các tình nguyện viên. Nếu hệ thống của bạn không hoạt động
có thể thay dấu "~" bằng từ "khoảng". Hoặc nếu giữ nguyên thì không có dấu cách giữa nó và số 100.
* "categories" được dịch là "hạng mục" từ nhiều chương trước.

2019-11-01 06:59 UTC, aivivn commented on chapters/ch26.md
> +| % tổng thể  |        75%            |      25%           |         50%         |
Bảng này không hiện đúng khi hiển thị. Mình không rõ lỗi tại đâu, bạn thử vài cách xem.

2019-11-01 06:59 UTC, aivivn commented on chapters/ch26.md
> +Trong ví dụ này, bạn có thể nhận ra rằng thuật toán của bạn đang có một thời gian đặc biệt khó khăn với các mẫu huấn luyện có nhiều nhiễu nền. Do đó, bạn có thể tập trung vào các kỹ thuật cho phép nó
Đoạn này giống Google translate quá :).

Từ "training" được dịch là "huấn luyện" chứ không phải "đào tạo"

2019-11-01 06:59 UTC, aivivn commented on chapters/ch26.md
> +Bạn cũng có thể kiểm tra kỹ xem một người có thể sao chép các clip âm thanh này hay không, đưa ra âm thanh đầu vào giống như thuật toán learning của bạn. Nếu có quá nhiều nhiễu nền mà đơn giản là khô
"thuật toán learning" -> "thuật toán học"

"human-level performance" ở chương sau có chỗ được dịch là "hiệu quả cấp con người".

Từ "performance" mình cũng đã dịch là "hiệu quả" từ đầu rồi.

2019-11-02 04:05 UTC, aivivn commented
Mình đóng PR này vì tác giả không phản hồi sau 3 ngày.

2019-11-02 04:17 UTC, seanphan commented
@aivivn ơi, mình đã resolved conflict của @tiepvupsu  3 ngày truớc. Bạn add comment 21 tiếng truớc mình sẽ cần thời gian update chứ bạn ?

![image](https://user-images.githubusercontent.com/5804000/68065880-363b7780-fd62-11e9-8bcd-da439aba2ef6.png)

2019-11-02 04:23 UTC, seanphan commented
Bạn mở PR lại mình sẽ update trong hôm nay nhé @aivivn

2019-11-02 04:28 UTC, tiepvupsu commented
> Bạn mở PR lại mình sẽ update trong hôm nay nhé @aivivn

Cảm ơn bạn. Mình nghĩ bạn có việc bận nên không thể tiếp tục được.

2019-11-02 04:58 UTC, aivivn commented
> @aivivn ơi, mình đã resolved conflict của @tiepvupsu 3 ngày truớc. Bạn add comment 21 tiếng truớc mình sẽ cần thời gian update chứ bạn ?
> 
> ![image](https://user-images.githubusercontent.com/5804000/68065880-363b7780-fd62-11e9-8bcd-da439aba2ef6.png)

Xin lỗi bạn. Mình không thấy bạn active mấy hôm nay, cả ở các PRs khác nên nghĩ bạn bận.

Mình nghĩ sẽ tốt hơn nếu chúng ta giải quyết từng PR trước khi sang PR khác. Phòng trường hợp một bạn có lý do cá nhân không thể tiếp tục làm việc trên một PR được thì công sức review sẽ đổ bể.

Cảm ơn bạn rất nhiều vì đã quay lại tiếp tục đóng góp.

2019-11-03 04:39 UTC, tiepvupsu approved these changes
Bản update trước của bạn khá ổn rồi. Mình chỉ sửa lại một vài chỗ và sửa format trước khi merge.

Cảm ơn bạn rất nhiều vì những đóng góp trong những chương vừa rồi.

2019-11-03 04:40 UTC, aivivn approved these changes

2019-11-03 04:40 UTC, merged

2019-11-03 13:16 UTC, seanphan commented
Cảm ơn bạn @tiepvupsu nhiều !