add the first draft for chap 31
aivivn/Machine-Learning-Yearning-Vietnamese-Translation pull request #248
Opened 2019-11-03 12:02 UTC by thhung

## Nếu bạn tạo Pull Request để dịch, vui lòng hoàn thành các thông tin dưới đây.

* [x] Đánh dấu [x] (không có dấu cách quanh x) thể hiện dấu tick vào các câu dưới đây cho các câu trả lời 'Có' hoặc 'Đúng'

* [x] Pull Request này được link tới một issue? Đánh số issue đó *ngay sau* dấu #215 

* [x] Bạn có kiến thức về Machine Learning không? Chúng tôi ưu tiên những người có trước kiến thức về Machine Learning để việc review được thuận tiện hơn.

* [x] Bạn đã đọc [Bảng thuật ngữ](https://github.com/aivivn/Machine-Learning-Yearning-Vietnamese-Translation/blob/master/glossary.md) chưa? Bạn cần dịch các thuật ngữ theo bảng thuật ngữ chung.

* [x] Tất cả các thuật ngữ trong chương này đã có trong [Bảng thuật ngữ](https://github.com/aivivn/Machine-Learning-Yearning-Vietnamese-Translation/blob/master/glossary.md) chưa? Nếu chưa, bạn có thể tạo một issue hoặc pull request mới để bổ sung nghĩa của từ đó vào Bảng thuật ngữ.

* [x] Pull request này đã sẵn sàng cho việc review chưa? Nếu đã sẵn sàng, bạn vui lòng gán label 'review wanted' cho pull request này. Nếu chưa, bạn vui lòng thêm cụm "[WIP]" (work in progress) vào trước tiêu đề của pull request.

## Lưu ý 
**Chỉ bắt đầu review khi mọi mục trên đây đều đã được tick.**

2019-11-03 16:40 UTC, tiepvupsu commented on chapters/ch31.md
> +-->
Bạn bỏ dòng mũi tên luôn nhé, để khi merge xong mình không cần dọn dẹp nữa. Cảm ơn bạn.

2019-11-03 22:28 UTC, thhung commented on chapters/ch31.md
> +-->
ok anh. De mai em don het cho.

2019-11-05 03:18 UTC, tiepvupsu requested changes
Chương này ngắn quá. Bạn sửa theo mấy comment của mình rồi mình sẽ approve.

Cảm ơn bạn.

2019-11-05 03:18 UTC, tiepvupsu commented on chapters/ch31.md
> +Đồ thị này thể  hiện độ chệch lớn, phương sai lớn hay cả hai?
hai dấu cách "thể  hiện"

2019-11-05 03:18 UTC, tiepvupsu commented on chapters/ch31.md
> +Đường cong lỗi huấn luyện màu xanh tương đối thấp và đường cong lỗi phát triển màu đỏ cao hơn nhiều so với lỗi huấn luyện màu xanh. Do đó, độ chệch nhỏ, nhưng phương sai lớn. Thêm dữ liệu huấn luyện
* Xanh lam hay xanh lục ;)

* "Thêm dữ liệu huấn luyện ~~(có~~ _nhiều_ khả năng ~~lớn)~~"

2019-11-05 03:18 UTC, tiepvupsu commented on chapters/ch31.md
> +Lần này, lỗi huấn luyện lớn, vì nó cao hơn nhiều so với mức hiệu suất mong muốn. Lỗi phát triển cũng lớn hơn nhiều so với lỗi huấn luyện. Vì vậy, bạn có độ chệch đáng kể  và phương sai cũng đáng kể.
* "Performance" được dịch là "hiệu quả" từ đầu cuốn sách. Bây giờ mình dịch chung như thế cho nhất quán. Sau nếu muốn sửa lại chỉ cần search and replace là được.

* Hai dấu cách "kể  và phương sai"

2019-11-05 08:03 UTC, thhung commented on chapters/ch31.md
> +Đồ thị này thể  hiện độ chệch lớn, phương sai lớn hay cả hai?
em viết trên VS code của ubuntu nên chỗ đó nó hiện 2 chữ này liền nhau => em cách ra 1 cái => lúc render thành 2 space. Để lúc nữa em sửa lại rồi push luôn.

2019-11-05 08:08 UTC, thhung commented on chapters/ch31.md
> +Đường cong lỗi huấn luyện màu xanh tương đối thấp và đường cong lỗi phát triển màu đỏ cao hơn nhiều so với lỗi huấn luyện màu xanh. Do đó, độ chệch nhỏ, nhưng phương sai lớn. Thêm dữ liệu huấn luyện
em định dịch là màu xanh da trời đấy.

2019-11-06 22:37 UTC, tiepvupsu commented on chapters/ch31.md
> +Đường cong lỗi huấn luyện màu xanh tương đối thấp và đường cong lỗi phát triển màu đỏ cao hơn nhiều so với lỗi huấn luyện màu xanh. Do đó, độ chệch nhỏ, nhưng phương sai lớn. Thêm dữ liệu huấn luyện
Em dịch là 'xanh lam' nhé, cho thống nhất với các chương trước.

2019-11-06 22:38 UTC, tiepvupsu approved these changes
Còn mấy lỗi nhỏ xíu, anh merge rồi sửa sau.

2019-11-06 22:38 UTC, merged