Dịch chương 54
aivivn/Machine-Learning-Yearning-Vietnamese-Translation pull request #352
Opened 2019-11-23 23:05 UTC by quangnhat185

## Nếu bạn tạo Pull Request để dịch, vui lòng hoàn thành các thông tin dưới đây.

* [x] Đánh dấu [x] (không có dấu cách quanh x) thể hiện dấu tick vào các câu dưới đây cho các câu trả lời 'Có' hoặc 'Đúng'

* [x] Pull Request này được link tới một issue? Đánh số issue đó *ngay sau* dấu `#`: close #343 

* [x] Bạn có kiến thức về Học Máy không? Chúng tôi ưu tiên những người có trước kiến thức về Học Máy để việc review được thuận tiện hơn.

* [x] Bạn đã đọc [Bảng thuật ngữ](https://github.com/aivivn/Machine-Learning-Yearning-Vietnamese-Translation/blob/master/glossary.md) chưa? Bạn cần dịch các thuật ngữ theo bảng thuật ngữ chung.

* [x] Tất cả các thuật ngữ trong chương này đã có trong [Bảng thuật ngữ](https://github.com/aivivn/Machine-Learning-Yearning-Vietnamese-Translation/blob/master/glossary.md) chưa? Nếu chưa, bạn có thể tạo một issue hoặc pull request mới để bổ sung nghĩa của từ đó vào Bảng thuật ngữ.

* [x] Bạn đã xóa cả dấu `-->` trong các dòng `--> _replace THIS LINE by your translation for the above line_` chưa?

* [x] Bản dịch của bạn có theo format của bản gốc không (`#` và số cho tiêu đề, **in đậm**, *in nghiêng*)?
 
* [x] Pull request này đã sẵn sàng cho việc review chưa?

## Lưu ý 
**Chỉ bắt đầu review khi mọi mục trên đây đều đã được tick.**

2019-11-24 05:17 UTC, tiepvupsu requested changes
Bài dịch khá tốt, trừ một số từ và câu em bỏ qua chưa dịch.
Từ "bounding box" anh có đề xuất là "khung bao" hoặc "khung chứa". Chắc phải thống nhất chọn một rồi cho mọi người quen dùng.

2019-11-24 05:17 UTC, tiepvupsu commented on chapters/ch54.md
> -
Em xóa nhầm dòng này rồi. Nguyên tắc trong markdown là hai đoạn khác nhau cách nhau bởi ít nhất 1 dòng trắng. Tiêu đề và nội dung được coi là hai đoạn khác nhau nên cần tách riêng ra.

2019-11-24 05:17 UTC, tiepvupsu commented on chapters/ch54.md
> +Cùng tiếp tục với ví dụ trên:
"this"  = "này"?

2019-11-24 05:17 UTC, tiepvupsu commented on chapters/ch54.md
> +Khi đó bộ phân loại giống mèo được nhận một ảnh bị cắt, và cho kết quả không chính xác là y=0, hoặc là không có con mèo nào trong hình.
"được nhận" -> "nhận"

"hoặc là" -> "tức" thì nghĩa rõ hơn.

2019-11-24 05:17 UTC, tiepvupsu commented on chapters/ch54.md
> +Bộ phát hiện mèo đã hoạt động không tốt. Tuy nhiên, một người có kỹ năng vẫn có thể nhận dạng mèo Siamese từ bức ảnh bị cắt. Trường hợp này chúng ta nên quy lỗi cho bộ phát hiện mèo, bộ phân loại giố
Chỗ "poorly cropped image" em dịch thiếu chữ "poor". Chữ này quan trọng vì nếu bức ảnh bị cắt mà đẹp đẽ thì sẽ biết ngay lỗi ở bộ phân loại giống mèo.

Anh đề xuất sửa một chút thành "từ bị ảnh bị cắt lệch"

2019-11-24 05:17 UTC, tiepvupsu commented on chapters/ch54.md
> +Nói cách khác, thực hiện thử nghiệm mà ở đó bạn cung cấp cho bộ phân loại giống mèo một đầu vào "hoàn hảo".
Em dịch thiếu câu thứ hai: "Có hai trường hợp:".

2019-11-24 05:17 UTC, tiepvupsu commented on chapters/ch54.md
> +* Trường hợp 1: Kể cả với một bounding box "hoàn hảo", bộ phân loại giống mèo vẫn đưa ra kết quả không chính xác y=0. Trường hợp này rõ ràng là bộ phân loại giống mèo có lỗi.
"_Trong_ ~~T~~ trường hợp này, rõ ràng là bộ phân loại giống mèo có lỗi."

2019-11-24 09:56 UTC, quangnhat185 commented on chapters/ch54.md
> +Bộ phát hiện mèo đã hoạt động không tốt. Tuy nhiên, một người có kỹ năng vẫn có thể nhận dạng mèo Siamese từ bức ảnh bị cắt. Trường hợp này chúng ta nên quy lỗi cho bộ phát hiện mèo, bộ phân loại giố
Hay quá anh ơi :smile:

2019-11-24 10:02 UTC, quangnhat185 commented
> Bài dịch khá tốt, trừ một số từ và câu em bỏ qua chưa dịch.
> Từ "bounding box" anh có đề xuất là "khung bao" hoặc "khung chứa". Chắc phải thống nhất chọn một rồi cho mọi người quen dùng.

Em vote cho từ "khung chứa" vì cảm giác đọc xuôi tai hơn.

2019-11-25 13:24 UTC, lkhphuc approved these changes

2019-11-26 18:03 UTC, tiepvupsu approved these changes

2019-11-26 18:03 UTC, merged