close #309 Dich chuong 48
aivivn/Machine-Learning-Yearning-Vietnamese-Translation pull request #360
Opened 2019-11-25 10:16 UTC by nerophung

## Nếu bạn tạo Pull Request để dịch, vui lòng hoàn thành các thông tin dưới đây.

* [x] Đánh dấu [x] (không có dấu cách quanh x) thể hiện dấu tick vào các câu dưới đây cho các câu trả lời 'Có' hoặc 'Đúng'

* [X] Pull Request này được link tới một issue? Đánh số issue đó *ngay sau* dấu `#`: close #

* [X] Bạn có kiến thức về Học Máy không? Chúng tôi ưu tiên những người có trước kiến thức về Học Máy để việc review được thuận tiện hơn.

* [X] Bạn đã đọc [Bảng thuật ngữ](https://github.com/aivivn/Machine-Learning-Yearning-Vietnamese-Translation/blob/master/glossary.md) chưa? Bạn cần dịch các thuật ngữ theo bảng thuật ngữ chung.

* [ ] Tất cả các thuật ngữ trong chương này đã có trong [Bảng thuật ngữ](https://github.com/aivivn/Machine-Learning-Yearning-Vietnamese-Translation/blob/master/glossary.md) chưa? Nếu chưa, bạn có thể tạo một issue hoặc pull request mới để bổ sung nghĩa của từ đó vào Bảng thuật ngữ.

* [X] Bạn đã xóa cả dấu `-->` trong các dòng `--> _replace THIS LINE by your translation for the above line_` chưa?

* [X] Bản dịch của bạn có theo format của bản gốc không (`#` và số cho tiêu đề, **in đậm**, *in nghiêng*)?
 
* [X] Pull request này đã sẵn sàng cho việc review chưa?

## Lưu ý 
**Chỉ bắt đầu review khi mọi mục trên đây đều đã được tick.**

2019-11-25 12:51 UTC, lkhphuc requested changes
Bản dịch hay rồi. Có một vài typo nhỏ bạn sửa lại nhé. :))

2019-11-25 12:51 UTC, lkhphuc commented on chapters/ch48.md
> +# 48. Nhiều ví dụ về học đầu-cuối hơn.
-> " 48. Thêm ~Nhiều~ những ví dụ về học đầu-cuối ~hơn~." 
Vì không phải "more than" nên mình thấy dịch vầy hay hơn cách dịch là "nhiều hơn"

2019-11-25 12:51 UTC, lkhphuc commented on chapters/ch48.md
> +Các thành phần sẽ làm việc như sau:
"làm việc" -> "hoạt động" . cái này preference của mình thôi

2019-11-25 12:51 UTC, lkhphuc commented on chapters/ch48.md
> +1. Tính toán các đặc trưng: Trích xuất các đặc trưng được thiết kế thủ công, ví dụ như đặc trưng MFCC (Hệ số Mel-frequency cepstrum), được sử dụng để nắm lấy nội dung của đoạn phát biểu trong khi bỏ
"nắm lấy" -> nắm bắt

2019-11-25 12:51 UTC, lkhphuc commented on chapters/ch48.md
> +2. Nhận diện các âm vị: Các nhà ngôn ngữ học tin rằng trong ngôn ngữ có các đơn vị cơ bản gọi là "âm vị." Ví dụ, âm bắt đầu "k" trong từ "keep" thì phát âm giống âm của "c" trong từ "cake". Hệ thống
giống âm ~của~ "c" trong từ "cake"

2019-11-25 12:51 UTC, lkhphuc commented on chapters/ch48.md
> +3. Nhận dạng cuối cùng: Dùng các chuỗi âm vị đã được nhận dạng, và cố gắng xâu chuỗi chúng lại với nhau thành một bản ghi thoại đầu ra.
"3. _Bộ nhận_ dạng cuối cùng:" . Thêm chữ bộ cho sát nghĩa từ recognizER.

2019-11-25 12:51 UTC, lkhphuc commented on chapters/ch48.md
> +3. Nhận dạng cuối cùng: Dùng các chuỗi âm vị đã được nhận dạng, và cố gắng xâu chuỗi chúng lại với nhau thành một bản ghi thoại đầu ra.
"ghi thoại _ở_ đầu ra."

2019-11-25 12:51 UTC, lkhphuc commented on chapters/ch48.md
> +Không phải mọi thành phần trong pipeline phải được học tập. Ví dụ, các nghiên cứu về "hoạch định chuyển động của robot" cần rất nhiều thuật toán cho bước hoạch định lộ trình của chiếc xe. Tuy nhiên c
"các nghiên cứu về "hoạch định chuyển động của robot" cần rất nhiều thuật toán" -> "đã có rất nhiều thuật toán cho ..."

2019-11-25 12:51 UTC, lkhphuc commented on chapters/ch48.md
> +Không phải mọi thành phần trong pipeline phải được học tập. Ví dụ, các nghiên cứu về "hoạch định chuyển động của robot" cần rất nhiều thuật toán cho bước hoạch định lộ trình của chiếc xe. Tuy nhiên c
"Tuy nhiên có nhiều những" -> "Trong đó có nhiều.."

2019-11-25 12:51 UTC, lkhphuc commented on chapters/ch48.md
> +Mặc dù phương pháp học đầu-cuối đã đạt được nhiều kết quả tốt, nó không phải luôn luôn là hướng đi tốt nhất. Vú dụ, phương phát nhận diện giọng nói đầu-cuối đạt kết quả tốt. Nhưng tôi cảm thấy hoài n
"Vú dụ" -> 😈
"phương phát" -> ...

2019-11-25 14:59 UTC, nerophung commented on chapters/ch48.md
> +Mặc dù phương pháp học đầu-cuối đã đạt được nhiều kết quả tốt, nó không phải luôn luôn là hướng đi tốt nhất. Vú dụ, phương phát nhận diện giọng nói đầu-cuối đạt kết quả tốt. Nhưng tôi cảm thấy hoài n
Mình đã sửa lại rồi, mn review lại nhé.

2019-11-25 19:51 UTC, tiepvupsu requested changes
Cảm ơn bạn. Bạn dịch rất hay.

Có một vài gợi ý về cách dùng từ, bạn xem xét lại nhé. Cảm ơn bạn.

2019-11-25 19:51 UTC, tiepvupsu commented on chapters/ch48.md
> +1. Tính toán các đặc trưng: Trích xuất các đặc trưng được thiết kế thủ công, ví dụ như đặc trưng MFCC (Hệ số Mel-frequency cepstrum), được sử dụng để nắm bắt nội dung của đoạn phát biểu trong khi bỏ
Mình nghĩ từ "speaker" đơn giản là "người nói" thôi. "Diễn giả" được dịch từ "presenter" khi một người đứng trước đám đông nói chuyện. Trong các ví dụ của cuốn sách này, speaker chỉ đơn giản là "người nói", âm thanh của họ được thu lại và hệ thống nhận dạng giọng nói phân tích giọng của người này.

2019-11-25 19:51 UTC, tiepvupsu commented on chapters/ch48.md
> +Mặt khác, một hệ thống đầu-cuối có thể nhận đầu vào là một đoạn hội thoại, và sẽ cố gắng cho ra trực tiếp một bản ghi thoại:
Cụm "audio clip" từ đầu sách được dịch là "đoạn âm thanh", bạn sửa lại cho nhất quán.

2019-11-25 19:51 UTC, tiepvupsu commented on chapters/ch48.md
> +Từ trước tới giờ, chúng ra chỉ mới mô tả các "pipeline" của học máy tuyến tính: đầu ra được truyền tuần tự từ giai đoạn này sang giai đoạn khác. Những Pipeline có thể phức tạp hơn như trong ví dụ về
Ý của đoạn này "các pipeline tuyến tính", nếu giữ như bạn dịch thì người đọc dễ bị hiểu nhầm thành "học máy tuyến tính". Mình đề xuất dịch lại là:
> Các "pipeline" tuyến tính của học máy: ...

Từ "Pipeline trong câu từ hai không cần viết hoa.

2019-11-25 19:51 UTC, tiepvupsu commented on chapters/ch48.md
> +Hệ thống bao gồm ba thành phần: Một thành phần giúp phát hiện những xe khác bằng việc sử dụng hình ảnh từ máy quay; Một thành phần khác phát hiện người đi bộ; thành phần cuối cùng hoạch định một lộ t
👍

2019-11-25 19:51 UTC, tiepvupsu commented on chapters/ch48.md
> +Không phải mọi thành phần trong pipeline phải được học tập. Ví dụ, các nghiên cứu về "hoạch định chuyển động của robot" đã có rất nhiều thuật toán cho bước hoạch định lộ trình của chiếc xe. Trong đó
Mặc dù từ "learn" có nghĩa là học, khi dùng với nghĩa bị động, mình ít thấy người ta dùng từ "học tập". Bạn có thể thay từ đó bằng "huấn luyện" nghe sẽ mượt hơn.

2019-11-25 19:51 UTC, tiepvupsu commented on chapters/ch48.md
> +Mặc dù phương pháp học đầu-cuối đã đạt được nhiều kết quả tốt, nó không phải luôn luôn là hướng đi tốt nhất. Ví dụ, phương pháp nhận diện giọng nói đầu-cuối đạt kết quả tốt. Nhưng tôi cảm thấy hoài n
Từ "nhận diện" dùng nhiều với mặt và các vật nhìn thấy. Từ "recognition" từ đầu sách được dịch là "nhận dạng". Có thể nó không khác nhau nhiều nhưng mình cần sự nhất quán.

2019-11-26 00:38 UTC, nerophung commented
Mình đã chỉnh sửa lại, mn reivew lại nhé.

2019-11-26 03:50 UTC, tiepvupsu approved these changes
Cảm ơn bạn. Bản dịch rất chất lượng, bạn phản rồi lại các comment cũng rất nhanh.

💯

2019-11-26 03:50 UTC, merged