Dịch chương 56
aivivn/Machine-Learning-Yearning-Vietnamese-Translation pull request #362
Opened 2019-11-25 12:24 UTC by ffyyytt

## Nếu bạn tạo Pull Request để dịch, vui lòng hoàn thành các thông tin dưới đây.

* [x] Đánh dấu [x] (không có dấu cách quanh x) thể hiện dấu tick vào các câu dưới đây cho các câu trả lời 'Có' hoặc 'Đúng'

* [x] Pull Request này được link tới một issue? Đánh số issue đó *ngay sau* dấu `#`: close #345 

* [x] Bạn có kiến thức về Học Máy không? Chúng tôi ưu tiên những người có trước kiến thức về Học Máy để việc review được thuận tiện hơn.

* [x] Bạn đã đọc [Bảng thuật ngữ](https://github.com/aivivn/Machine-Learning-Yearning-Vietnamese-Translation/blob/master/glossary.md) chưa? Bạn cần dịch các thuật ngữ theo bảng thuật ngữ chung.

* [x] Tất cả các thuật ngữ trong chương này đã có trong [Bảng thuật ngữ](https://github.com/aivivn/Machine-Learning-Yearning-Vietnamese-Translation/blob/master/glossary.md) chưa? Nếu chưa, bạn có thể tạo một issue hoặc pull request mới để bổ sung nghĩa của từ đó vào Bảng thuật ngữ.

* [x] Bạn đã xóa cả dấu `-->` trong các dòng `--> _replace THIS LINE by your translation for the above line_` chưa?

* [x] Bản dịch của bạn có theo format của bản gốc không (`#` và số cho tiêu đề, **in đậm**, *in nghiêng*)?
 
* [x] Pull request này đã sẵn sàng cho việc review chưa?

## Lưu ý 
**Chỉ bắt đầu review khi mọi mục trên đây đều đã được tick.**

2019-11-25 16:09 UTC, vinbrule requested changes
sửa và dịch lại cho rõ nghĩa, không dịch từng từ một

2019-11-25 16:09 UTC, vinbrule commented on chapters/ch56.md
> +Thực hiện phân tích lỗi trên các thuật toán học giống với việc sử dụng khoa học dữ liệu phân tích lỗi trên các hệ thống học máy để biết chính xác những việc cần làm kế tiếp. Ở mức cơ bản nhất, phân t
..phân tích lỗi của thuật toán học, không có "các"..
-- trên các hệ thống học máy ==> của hệ thống học máy

2019-11-25 16:09 UTC, van-tienhoang commented on chapters/ch56.md
> +Cách biệt về chất lượng của việc xác định xe và chất lượng mức con người trong việc xác định xe là bao?
+ cách biệt về khả năng xác định xe giữa con người và phần thuật toán xác định xe

2019-11-25 16:09 UTC, van-tienhoang commented on chapters/ch56.md
> ---> _replace THIS LINE by your translation for the above line_
cách biệt về khả năng phát hiện người đi bộ giữa thuật toán và con người

2019-11-25 17:20 UTC, vinbrule requested changes

2019-11-25 17:20 UTC, van-tienhoang commented on chapters/ch56.md
> +3. Cách biệt của toàn hệ thống và con người? Ở đây, con người phải hoạch định một con đường cho chiếc xe từ đầu ra của hai pipeline trước đó (không phải truy cập vào hình ảnh). Nói cách khác, so sánh
3. Cách biệt giữa khả năng của toàn hệ thống và con người tới cỡ nào? Đối với con người, chúng ta giả định rằng con người  tính đường đi cho xe mà chỉ dựa vào kết quả đầu ra của hai pipeline trước đó (thay vi dựa vào hình ảnh camera). Nói cách khác, với cùng thông tin đầu, khả năng ước lượng đường đi của thuật toán so với con người  sẽ như thế nào?

2019-11-26 10:31 UTC, ngdthanhcs commented on chapters/ch56.md
> +3. Cách biệt giữa khả năng của toàn hệ thống và con người tới cỡ nào? Đối với con người, chúng ta giả định rằng con người tính đường đi cho xe mà chỉ dựa vào kết quả đầu ra của hai pipeline trước đó
- 

> "previous two pipeline components"
ở đây pipeline là tính từ bổ nghĩa cho components, vậy nên dịch hai pipeline trước đó là không đúng và sẽ gây nhầm lẫn, vì mỗi pipeline là một chuỗi xử lí riêng biệt,

2019-11-26 10:51 UTC, ngdthanhcs requested changes

2019-11-26 10:51 UTC, ngdthanhcs commented on chapters/ch56.md
> the previous two pipeline components

ở đây pipeline là tính từ bổ nghĩa cho components chứ không phải danh từ. Nên dịch là "hai pipeline trước đó" sẽ sai và gây nhầm lẫn, vì mỗi pipeline là một chuỗi xử lí độc lập

=> kết quả đầu ra của chuỗi hai thành phần xử lí bên trên

2019-11-26 13:08 UTC, van-tienhoang commented on chapters/ch56.md
okay :)

2019-11-29 00:23 UTC, tiepvupsu reviewed
Mình có để lại một số gợi ý. Nếu bạn đồng ý thì chỉ cần ấn nút "Commit suggestion" để chấp nhận các gợi ý đó.

2019-11-29 00:23 UTC, tiepvupsu commented on chapters/ch56.md
> +Thực hiện phân tích lỗi của thuật toán học giống với việc sử dụng khoa học dữ liệu phân tích lỗi của hệ thống học máy để biết chính xác những việc cần làm kế tiếp. Cơ bản nhất, phân tích lỗi ở từng p
Từ "performance" được thống nhất dịch là "chất lượng".
```suggestion
Thực hiện phân tích lỗi của thuật toán học giống với việc sử dụng khoa học dữ liệu phân tích lỗi của hệ thống học máy để biết chính xác những việc cần làm kế tiếp. Cơ bản nhất, phân tích lỗi từng phần sẽ cho ta biết được chất lượng của (những) phần nào cần được cải thiện.
```

2019-11-29 00:23 UTC, tiepvupsu commented on chapters/ch56.md
> +Giả sử bạn có bộ dữ liệu về khách hàng mua đồ trên một trang mạng. Một nhà khoa học dữ liệu có thể có rất nhiều cách khác nhau để phân tích dữ liệu đó. Người đó có thể đưa ra nhiều kết luận khác nhau
```suggestion
Giả sử bạn có bộ dữ liệu về khách hàng mua đồ trên một trang mạng. Một nhà khoa học dữ liệu có thể có rất nhiều cách khác nhau để phân tích dữ liệu đó. Người đó có thể đưa ra nhiều kết luận khác nhau như có nên tăng giá, giá trị vòng đời khách hàng đạt được thông qua các chiến dịch tiếp thị khác nhau, v.v. Không có một việc phân tích dữ liệu "chuẩn mực" nào, và có thể có rất nhiều kết luận hữu ích có thể rút ra. Tương tự, không chỉ có một cách "chuẩn mực" cho việc thực hiện phân tích lỗi. Thông qua các chương này bạn đã học được những cách phổ biến nhất để rút ra những nhận định chính xác về hệ thống học máy của bạn, nhưng bạn cũng nên thử nghiệm những phương pháp phân tích lỗi khác.
```

2019-11-29 00:23 UTC, tiepvupsu commented on chapters/ch56.md
> +Chúng ta hãy quay trở lại ứng dụng xe tự lái, trong đó thuật toán phát hiện xe đưa ra vị trí (có thể có thêm vận tốc) của những chiếc xe gần đó, thuật toán phát hiện người đi bộ đưa ra vị trí của ngư
```suggestion
Chúng ta hãy quay trở lại ứng dụng xe tự lái, trong đó thuật toán phát hiện xe đưa ra vị trí (có thể có thêm vận tốc) của những chiếc xe gần đó, thuật toán phát hiện người đi bộ đưa ra vị trí của người đi bộ gần đó, và hai đầu ra này cuối cùng được sử dụng để hoạch định đường đi cho xe.
```

2019-11-29 00:23 UTC, tiepvupsu commented on chapters/ch56.md
> +Để kiểm tra lỗi pipeline này, thay vì tuân thủ nghiêm ngặt quy trình bạn đã thấy trong chương trước, bạn nên đặt những câu hỏi như:
```suggestion
Để kiểm tra lỗi pipeline này, thay vì tuân thủ nghiêm ngặt quy trình đã thấy trong chương trước, bạn nên đặt những câu hỏi như:
```

2019-11-29 00:23 UTC, tiepvupsu commented on chapters/ch56.md
> +1. Cách biệt về khả năng xác định xe giữa con người và phần thuật toán xác định xe?
```suggestion
1. Cách biệt về khả năng xác định xe giữa thuật toán và con người là bao xa?
```

2019-11-29 00:23 UTC, tiepvupsu commented on chapters/ch56.md
> +2. Cách biệt về khả năng phát hiện người đi bộ giữa thuật toán và con người?
```suggestion
2. Cách biệt về khả năng phát hiện người đi bộ giữa thuật toán và con người là bao xa?
```

2019-11-29 00:23 UTC, tiepvupsu commented on chapters/ch56.md
> +3. Cách biệt giữa khả năng của toàn hệ thống và con người tới cỡ nào? Đối với con người, chúng ta giả định rằng con người tính đường đi cho xe mà chỉ dựa vào kết quả đầu ra của chuỗi hai thành phần x
```suggestion
3. Cách biệt giữa khả năng của toàn hệ thống và con người tới cỡ nào? Ở đây, chất lượng của con người được giả sử là cách con người tính đường đi cho xe chỉ dựa vào kết quả đầu ra từ hai thành phần trước đó trong pipeline (thay vì dựa vào hình ảnh camera). Nói cách khác, với cùng thông tin đầu vào, khả năng ước lượng đường đi của thuật toán so với con người sẽ như thế nào?
```

2019-11-29 00:23 UTC, tiepvupsu commented on chapters/ch56.md
> +Nếu bạn thấy rằng một trong những thành phần thua xa chất lượng mức con người, thì bây giờ bạn biết phần nào là cần phải được cải thiện. Hãy tập trung vào việc cải thiện hiệu suất của phần đó.
```suggestion
Nếu bạn thấy rằng một trong những thành phần này thua xa chất lượng mức con người, thì bây giờ bạn biết phần nào cần được cải thiện. Hãy tập trung vào việc cải thiện chất lượng của phần đó.
```

2019-11-29 00:23 UTC, tiepvupsu commented on chapters/ch56.md
> +Nhiều quy trình phân tích lỗi hoạt động tốt nhất khi chúng ta đang cố gắng tự động hóa một thứ gì đó mà con người có thể làm do đó có thể so sánh với con người. Hầu hết các ví dụ trước của chúng ta c
```suggestion
Nhiều quy trình phân tích lỗi hoạt động tốt nhất khi chúng ta cố gắng tự động hóa một thứ gì đó mà con người có thể làm, do đó có thể so sánh với con người. Hầu hết các ví dụ trước của chúng ta ngầm giả định điều này. Nếu bạn đang xây dựng một hệ thống học máy trong đó đầu ra hoặc một số thành phần trung gian đang làm những việc mà thậm chí con người không thể làm tốt, thì một trong số những quy trình này sẽ không được áp dụng.
```

2019-11-29 00:23 UTC, tiepvupsu commented on chapters/ch56.md
> +Đây là một thuận lợi của việc giải quyết các vấn đề mà con người có thể giải quyết--bạn có các công cụ phân tích lỗi mạnh mẽ, do đó bạn có thể giúp cho nhóm của bạn làm việc hiệu quả hơn.
```suggestion
Đây là một thuận lợi của việc giải quyết các vấn đề mà con người có thể giải quyết--bạn có các công cụ mạnh mẽ để phân tích lỗi, do đó bạn có thể ưu tiên các công việc trong nhóm một cách hiệu quả hơn.
```

2019-11-30 00:04 UTC, tiepvupsu commented
@ffyyytt có tiếp tục với PR này nữa không? Mình thấy PR này sắp xong rồi.

2019-11-30 03:46 UTC, ffyyytt commented
> @ffyyytt có tiếp tục với PR này nữa không? Mình thấy PR này sắp xong rồi.

Dạ có ạ, do em không thấy gợi ý của anh.

2019-11-30 03:48 UTC, tiepvupsu approved these changes

2019-11-30 03:48 UTC, merged