Dịch Chương 52
aivivn/Machine-Learning-Yearning-Vietnamese-Translation pull request #363
Opened 2019-11-25 15:26 UTC by khoapip

## Nếu bạn tạo Pull Request để dịch, vui lòng hoàn thành các thông tin dưới đây.

* [x] Đánh dấu [x] (không có dấu cách quanh x) thể hiện dấu tick vào các câu dưới đây cho các câu trả lời 'Có' hoặc 'Đúng'

* [x] Pull Request này được link tới một issue? Đánh số issue đó *ngay sau* dấu `#`: close #

* [x] Bạn có kiến thức về Học Máy không? Chúng tôi ưu tiên những người có trước kiến thức về Học Máy để việc review được thuận tiện hơn.

* [x] Bạn đã đọc [Bảng thuật ngữ](https://github.com/aivivn/Machine-Learning-Yearning-Vietnamese-Translation/blob/master/glossary.md) chưa? Bạn cần dịch các thuật ngữ theo bảng thuật ngữ chung.

* [x] Tất cả các thuật ngữ trong chương này đã có trong [Bảng thuật ngữ](https://github.com/aivivn/Machine-Learning-Yearning-Vietnamese-Translation/blob/master/glossary.md) chưa? Nếu chưa, bạn có thể tạo một issue hoặc pull request mới để bổ sung nghĩa của từ đó vào Bảng thuật ngữ.

* [x] Bạn đã xóa cả dấu `-->` trong các dòng `--> _replace THIS LINE by your translation for the above line_` chưa?

* [x] Bản dịch của bạn có theo format của bản gốc không (`#` và số cho tiêu đề, **in đậm**, *in nghiêng*)?
 
* [x] Pull request này đã sẵn sàng cho việc review chưa?

## Lưu ý 
**Chỉ bắt đầu review khi mọi mục trên đây đều đã được tick.**

2019-11-25 15:30 UTC, khoapip commented
Bài này có một số từ em thắc mắc không biết dịch như thế nào cho chuẩn: 
- Rich : phức tạp 
- TTS (Text to Speech) : văn bản chuyển dịch
- Transcription: Chuyển văn bản thành giọng nói
- Caption: chú thích
- accelerating: Câu này ở câu cuối, em dịch kha khá khác bản gốc theo ý hiểu của em. Mọi người cho ý kiến ạ.

2019-11-25 20:22 UTC, tiepvupsu requested changes

2019-11-25 20:22 UTC, tiepvupsu commented on chapters/ch52.md
> +Trực tiếp học những đầu ra phức tạp.
Oops, thiếu `#52. ` ở đầu.

Từ "rich" bạn dịch là "phức tạp" cũng ok ở đây.

2019-11-25 20:22 UTC, tiepvupsu commented on chapters/ch52.md
> +Một thuật toán phân loại sẽ nhận đầu vào là một ảnh x rồi trả về một số nguyên thể hiện nhãn phân loại của đồ vật trong ảnh đó. Thay vào đó, liệu một thuật toán có thể có đầu ra là một câu văn miêu t
Câu thứ hai mình đề xuất gọn hơn: "Thay vào đó, liệu một thuật toán có thể đưa ra một mô tả hoàn chỉnh cho bức ảnh?"

2019-11-25 20:22 UTC, tiepvupsu commented on chapters/ch52.md
> +> | :----------------------- | :---------------------- | :------------------|
Đoạn này bạn không phải đưa mấy dấu `> ` nữa. Các dấu này chỉ áp dụng với các câu tiếng Anh.

2019-11-25 20:22 UTC, tiepvupsu commented on chapters/ch52.md
> +> | Gợi ý sản phẩm           | Đặc trưng của sản phẩm và người dùng | Chance of purchas |
"Chance of purchase" -> "khả năng mua sản phẩm". Đúng ra dịch là "Xác suất mua sản phẩm" sẽ dễ hiểu hơn. Nhưng mình nghĩ cái nào cũng ok.

2019-11-25 20:22 UTC, tiepvupsu commented on chapters/ch52.md
> +Một trong những hướng phát triển thú vị nhất của học sâu đầu cuối là nó cho phép chúng ta trực tiếp học được những kết quả phức tạp hơn rất nhiều so với việc chỉ trả về một con số [cần dịch lại]. Tro
"học sâu đầu-cuối"
> Một trong những hướng phát triển thú vị nhất của học sâu ~~đầu cuối~~ _đầu-cuối_ là nó cho phép chúng ta trực tiếp học ~~được~~ những kết quả phức tạp hơn ~~rất nhiều so với việc chỉ trả về~~ một con số _rất nhiều_ ~~[cần dịch lại]~~.

2019-11-25 20:22 UTC, tiepvupsu commented on chapters/ch52.md
> +| Nhận dạng giọng nói | Audio                 | văn bản chuyển dịch| Hannun et al., 2015  |
"audio" -> "âm thanh"

"transcription" -> "bản ghi thoại"

2019-11-25 20:22 UTC, tiepvupsu commented on chapters/ch52.md
> +| Trả lời câu hỏi     | (Văn bản, Câu hỏi) theo cặp| Câu trả lời   | Bordes et al., 2015  |
"Question answering" -> "Hỏi đáp"

"(Text, Question) pair" -> "cặp (Văn bản, Câu hỏi)"

2019-11-26 04:04 UTC, tiepvupsu commented on chapters/ch52.md
> +| Chuyển văn bản thành giọng nói | Đặc trưng văn bản  | Audio         | van der Oord et al., 2016 |
"Audio" -> "âm thanh"

"TTS" = "Text to Speach" -> "Văn bản sang giọng nói"

2019-11-26 15:00 UTC, lkhphuc requested changes

2019-11-26 15:00 UTC, lkhphuc commented on chapters/ch52.md
> +Trực tiếp học những đầu ra phức tạp.
Rich cũng có thể dịch thành "phong phú", mình thấy sát nghĩa hơn.

2019-11-26 15:00 UTC, lkhphuc commented on chapters/ch52.md
> +Một thuật toán phân loại sẽ nhận đầu vào là một ảnh x rồi trả về một số nguyên thể hiện nhãn phân loại của đồ vật trong ảnh đó. Thay vào đó, liệu một thuật toán có thể có đầu ra là một câu văn miêu t
"một _câu_ mô tả hoàn chỉnh", mình góp ý thêm chữ "câu".

2019-11-26 15:00 UTC, lkhphuc commented on chapters/ch52.md
> +| Trả lời câu hỏi     | (Văn bản, Câu hỏi) theo cặp| Câu trả lời   | Bordes et al., 2015  |
"Answer text " -> "Văn bản trả lời"

2019-11-26 15:00 UTC, lkhphuc commented on chapters/ch52.md
> +Đây là một xu hướng đang ngày càng phát triển trong học sâu. Với các cặp có nhãn (đầu vào, đầu ra) phù hợp, đôi khi bạn có thể học đầu cuối ngay cả khi đầu ra là một câu, hình ảnh, âm thanh hoặc các
"phức tạp hơn nhiều so với đầu ra của việc học truyền thống." -> "phong phú hơn nhiều thay vì chỉ là một con số."

2019-11-26 15:31 UTC, nmdang commented on chapters/ch52.md
> +Một trong những hướng phát triển thú vị nhất của học sâu đầu cuối là nó cho phép chúng ta trực tiếp học được những kết quả phức tạp hơn rất nhiều so với việc chỉ trả về một con số [cần dịch lại]. Tro
mạng neural -->  mạng nơ-ron

2019-11-27 05:24 UTC, tiepvupsu commented on chapters/ch52.md
> +Trực tiếp học những đầu ra phức tạp.
@khoapip em chỉ cần ấn vào "commit suggestion" là nó tự đổi luôn ở đây nhé.
```suggestion
# 52. Trực tiếp học những đầu ra phức tạp.
```

2019-11-28 07:39 UTC, aivivn commented
@khoapip bạn có tiếp tục theo PR này không?

2019-11-28 11:13 UTC, khoapip commented
Em có ạ, tầm 1-2 tiếng nữa em push bản update

2019-11-28 11:49 UTC, khoapip commented
Em đã update bản gần nhất ạ. Có một số đoạn dịch phần "more complex than a single number" em có đổi thành "phức tạp hơn rất nhiều so với đầu ra của việc học truyền thống" theo ý hiểu của em, do dịch một số nghe khá cụt, nếu không hợp lý em sẽ đổi lại ạ.
Và còn từ "phong phú" với "phức tạp" em cũng chưa biết nên sửa lại không.

2019-11-28 18:16 UTC, tiepvupsu submitted a review, later dismissed
Bản này đã khá tốt rồi.

Cụm "more complex than a single number" dịch như hiện tại cũng ok. Từ "rich" theo mình dịch là "phức tạp" thuận tai hơn "phong phú" nhiều.

Em xem thêm mấy gợi ý của anh nhé @khoapip.

2019-11-28 18:16 UTC, tiepvupsu commented on chapters/ch52.md
> +# 52. Trực tiếp học những đầu ra phức tạp.
```suggestion
# 52. Trực tiếp học những đầu ra phức tạp
```

2019-11-28 18:16 UTC, tiepvupsu commented on chapters/ch52.md
> +Một thuật toán phân loại sẽ nhận đầu vào là một ảnh x rồi trả về một số nguyên thể hiện nhãn phân loại của đồ vật trong ảnh đó. Thay vào đó, liệu một thuật toán có thể đưa ra một câu mô tả hoàn chỉnh
```suggestion
Một thuật toán phân loại sẽ nhận đầu vào là một ảnh x rồi trả về một số nguyên thể hiện nhãn phân loại của đồ vật trong ảnh đó. Thay vào đó, liệu một thuật toán có thể đưa ra một câu mô tả hoàn chỉnh cho bức ảnh đó? 
```

2019-11-28 18:16 UTC, tiepvupsu commented on chapters/ch52.md
>  > *x* = ![img](../imgs/C52_01.png)
```suggestion
*x* = 
![img](../imgs/C52_01.png)
```

2019-11-28 18:16 UTC, tiepvupsu commented on chapters/ch52.md
> +*y* = "Một chiếc xe buýt màu vàng đang đi xuống một con đường với cây xanh và cỏ xanh ở nền."
```suggestion
*y* = "Một chiếc xe buýt màu vàng đang đi xuống một con đường với nền xanh của cây cỏ."
```

2019-11-28 22:23 UTC, thhung commented on chapters/ch52.md
> +Một trong những hướng phát triển thú vị nhất của học sâu đầu-cuối là nó cho phép chúng ta trực tiếp học những kết quả phức tạp hơn rất nhiều so với đầu ra của việc học truyền thống. Trong ví dụ chú t
MÌnh nghĩ đoạn này: 

> 
Một trong những hướng phát triển thú vị nhất của học sâu đầu-cuối là nó cho phép chúng ta trực tiếp học những kết quả phức tạp hơn rất nhiều so với ~đầu ra của việc học truyền thống~ đầu ra là một nhãn (một số)

để giữ nguyên ý của tác giả.

2019-11-29 00:30 UTC, tiepvupsu commented on chapters/ch52.md
> +Một trong những hướng phát triển thú vị nhất của học sâu đầu-cuối là nó cho phép chúng ta trực tiếp học những kết quả phức tạp hơn rất nhiều so với đầu ra của việc học truyền thống. Trong ví dụ chú t
@thhung chỗ này khá minor, theo mình cũng không khác nhau nhiều. Mình approve trước, ở giai đoạn hai chúng ta sẽ sửa kỹ lại ngôn ngữ.

2019-11-29 00:30 UTC, tiepvupsu approved these changes
Cảm ơn @khoapip.

2019-11-29 00:30 UTC, merged