Revise Chương 20-23
aivivn/Machine-Learning-Yearning-Vietnamese-Translation pull request #415
Opened 2019-12-04 06:58 UTC by rootonchair

## Nếu bạn tạo Pull Request để dịch, vui lòng hoàn thành các thông tin dưới đây.

* [x] Đánh dấu [x] (không có dấu cách quanh x) thể hiện dấu tick vào các câu dưới đây cho các câu trả lời 'Có' hoặc 'Đúng'

* [x] Pull Request này được link tới một issue? Đánh số issue đó *ngay sau* dấu `#`: close #384 

* [x] Bạn có kiến thức về Học Máy không? Chúng tôi ưu tiên những người có trước kiến thức về Học Máy để việc review được thuận tiện hơn.

* [x] Bạn đã đọc [Bảng thuật ngữ](https://github.com/aivivn/Machine-Learning-Yearning-Vietnamese-Translation/blob/master/glossary.md) chưa? Bạn cần dịch các thuật ngữ theo bảng thuật ngữ chung.

* [x] Pull request này đã sẵn sàng cho việc review chưa?

## Lưu ý 
**Chỉ bắt đầu review khi mọi mục trên đây đều đã được tick.**

2019-12-04 07:02 UTC, rootonchair commented
Một số chỗ mình chưa giải quyết:

* overfit/underfit/overfitting/underfitting vẫn chưa được dịch
* "insight" được dịch là "cái nhìn sâu sắc"/"hiểu biết sâu sắc" khá là ... google translate. Mình mong muốn có thể có cách dịch khác phù hợp hơn.

2019-12-04 07:41 UTC, tiepvupsu reviewed
Em sửa lại khá ổn rồi.

Về các từ "fit", "overfitting", "underfitting" em dịch như ở thảo luận kia là được rồi. Mình không nên để cái đó block quá lâu.

Em lưu ý sửa luôn cả từ "regularization" ở các chương khác nữa nhé.

2019-12-04 07:41 UTC, tiepvupsu commented on chapters/ch20.md
> +Mặc dù có thêm dữ liệu không làm tổn hại đến hiệu quả, thật không may điều này không phải lúc nào cũng mang lại hiệu quả nhiều như bạn mong đợi. Việc thu thập thêm dữ liệu có thể trở nên lãng phí thờ
Câu đầu tiên lặp hai từ "hiệu quả", anh vẫn chưa biết giải quyết sao.

Từ "you" trong tiếng Anh có thể có nhưng khi dịch mình có thể bỏ. Sao cho đơn giản, "thuần" Việt,  mà không làm thay đổi nghĩa.
```suggestion
Mặc dù có thêm dữ liệu không làm tổn hại đến hiệu quả, thật không may, điều này không phải lúc nào cũng mang lại hiệu quả nhiều như mong đợi. Việc thu thập thêm dữ liệu có thể trở nên lãng phí thời gian. Vậy làm thể nào để bạn quyết định khi nào nên thêm dữ liệu, khi nào không nên?
```

2019-12-04 07:41 UTC, tiepvupsu commented on chapters/ch22.md
> +[8] Nếu con số này là âm, bạn đang làm tốt hơn ở trên tập huấn luyện so với tỉ lệ lỗi tối ưu. Điều này có nghĩa là bạn đang overfitting tập huấn luyện và thuật toán đã ghi nhớ quá mức tập huấn luyện.
```suggestion
[8] Nếu con số này là âm, bạn đang làm tốt hơn ở trên tập huấn luyện so với tỉ lệ lỗi tối ưu. Điều này có nghĩa là bạn đang overfitting tập huấn luyện và thuật toán đã ghi nhớ quá mức tập huấn luyện. Bạn nên tập trung vào các phương pháp giảm phương sai hơn là các phương pháp giảm độ chệch sâu hơn.
```

2019-12-04 07:56 UTC, rootonchair commented on chapters/ch22.md
> +[8] Nếu con số này là âm, bạn đang làm tốt hơn ở trên tập huấn luyện so với tỉ lệ lỗi tối ưu. Điều này có nghĩa là bạn đang overfitting tập huấn luyện và thuật toán đã ghi nhớ quá mức tập huấn luyện.
> Nếu con số này là âm, bạn đang làm tốt hơn ở trên tập huấn luyện so với tỉ lệ lỗi tối ưu. Điều này có nghĩa là bạn đang overfitting tập huấn luyện và thuật toán đã ghi nhớ quá mức tập huấn luyện. Bạn nên tập trung vào các phương pháp giảm phương sai hơn là các phương pháp giảm độ chệch sâu hơn.

Em vẫn chưa hiểu suggest này lắm. Anh giải thích giúp em được không? 
Em hiểu ý tác giả là "nên kiếm cách giảm phương sai chứ không nên kiếm các phương pháp làm giảm độ chệch khác".

2019-12-04 07:59 UTC, tiepvupsu commented
À anh quên, vì nhiều chương khác cũng đang dùng "fit", "overfit", "underfit" nên em cứ giữ nguyên đã. Khi nào thay thì thay một loạt các từ này.

2019-12-04 08:00 UTC, tiepvupsu commented on chapters/ch22.md
> +[8] Nếu con số này là âm, bạn đang làm tốt hơn ở trên tập huấn luyện so với tỉ lệ lỗi tối ưu. Điều này có nghĩa là bạn đang overfitting tập huấn luyện và thuật toán đã ghi nhớ quá mức tập huấn luyện.
Oh, chỗ này từ "further" nghĩa là "tiếp tục", anh nghĩ dịch "khác" là chuẩn rồi. Để anh sửa lại.

2019-12-04 08:01 UTC, rootonchair commented
Vâng. Mà có một vài chỗ các bạn để luôn là "underfitting" với "overfitting" luôn nên khi nào thay anh kiểm tra luôn các từ này nhé

2019-12-04 08:05 UTC, tiepvupsu commented
> n để luôn là "underfitting" với "overfitting" luôn nên khi nào thay anh kiểm tra luôn các từ này nhé

Để anh sang cái issue note lại. Em đừng đóng issue đó nhé.

2019-12-04 08:10 UTC, rootonchair reviewed
@tiepvupsu em suggest như vầy anh thấy sao?

2019-12-04 08:10 UTC, rootonchair commented on chapters/ch20.md
> +Mặc dù có thêm dữ liệu không làm tổn hại đến hiệu quả, thật không may, điều này không phải lúc nào cũng mang lại hiệu quả nhiều như mong đợi. Việc thu thập thêm dữ liệu có thể trở nên lãng phí thời g
```suggestion
Mặc dù có thêm dữ liệu không làm tổn hại gì, thật không may, điều này không phải lúc nào cũng mang lại hiệu quả nhiều như mong đợi. Việc thu thập thêm dữ liệu có thể trở nên lãng phí thời gian. Vậy làm thể nào để bạn quyết định khi nào nên thêm dữ liệu, khi nào không nên?
```

2019-12-04 08:11 UTC, tiepvupsu commented on chapters/ch23.md
> +Giả sử bạn đang áp dụng học sâu, với điều chuẩn L2 hoặc dropout, với tham số điều chuẩn hoạt động tốt nhất tập phát triển. Nếu bạn tăng kích thuớc mô hình, thuờng thì chất lượng của mô hình sẽ giữ ng
Nếu thay thì thay cả các chương trước luôn em ơi. Mấy từ "fitting" chưa thay trong glossary nên mình dồn về cuối thôi.

2019-12-04 08:11 UTC, tiepvupsu submitted a review, later dismissed
Em có thể merge nhưng cần thay regularization ở các chương khác nữa.

2019-12-04 08:12 UTC, rootonchair commented
> Em có thể merge nhưng cần thay regularization ở các chương khác nữa.

Em nghĩ sẽ để nguyên rồi thay đồng loạt luôn. Thay bây giờ sẽ dễ conflict

2019-12-04 08:30 UTC, ngcthuong reviewed
Cảm ơn bài dịch của bạn về 4 chương dài ...ngoẵng này. Mình có một vài comments bên dưới bạn tham khảo. 

Về cơ bản có một số từ chưa dịch như "clip", từ "chúng ta" nên được dịch là "ta" cho hợp với các chương trước đó. Các từ "bạn" và "của bạn" được dùng khá nhiều mà phần lớn có thể được lược bỏ. 

Có sự không đồng nhất về dịch từ "training error" tỉ lệ lỗi huấn luyện (khi có "tỉ lệ, khi không). 

Bạn tham khảo nhé. 

Cheer :D

2019-12-04 08:30 UTC, ngcthuong commented on chapters/ch20.md
> +Mặc dù có thêm dữ liệu không làm tổn hại đến hiệu quả, thật không may điều này không phải lúc nào cũng mang lại hiệu quả nhiều như bạn mong đợi. Việc thu thập thêm dữ liệu có thể trở nên lãng phí thờ
- Mặc dù có thêm dữ liệu không làm tổn hại đến hiệu quả, --> "không làm giảm" có vẻ hợp hơn. Tổn hại nghe giống dạng tổn hại vật lý và tình thần hơn.
-  Vậy làm thể nào để bạn quyết định khi nào nên **_hoặc không nên_** thêm dữ liệu ~~,khi nào không nên~~?

2019-12-04 08:30 UTC, ngcthuong commented on chapters/ch20.md
> +Có hai nguồn chính dẫn đến lỗi trong học máy: độ chệch và phương sai. Hiểu được chúng sẽ giúp bạn quyết định liệu rằng có đáng bỏ thời gian ra để thêm dữ liệu, cũng như áp dụng các kỹ thuật khác để c
- Có thể bỏ từ "có" và "ra", 
> Hiểu được chúng sẽ giúp bạn quyết định liệu ~~rằng~~ có đáng bỏ thời gian ra để thêm dữ liệu ~~, cũng như~~ **_hay_** áp dụng các kỹ thuật khác để cải thiện chất lượng của mô hình **_hay không_**.

2019-12-04 08:30 UTC, ngcthuong commented on chapters/ch20.md
> +Giả sử bạn hy vọng xây dựng được một bộ nhận dạng mèo với 5% lỗi. Hiện tại, tập huấn luyện của bạn có tỉ lệ lỗi là 15%, và tập phát triển có tỉ lệ lỗi là 16%. Trong trường hợp này, việc thêm dữ liệu
> Hiện tại, tập huấn luyện và tập phát triển ~~của bạn~~ có tỉ lệ lỗi **_lần lượt_** là 15% và ~~tập phát triển có tỉ lệ lỗi là~~ 16%.

2019-12-04 08:30 UTC, ngcthuong commented on chapters/ch20.md
> +Giả sử bạn hy vọng xây dựng được một bộ nhận dạng mèo với 5% lỗi. Hiện tại, tập huấn luyện của bạn có tỉ lệ lỗi là 15%, và tập phát triển có tỉ lệ lỗi là 16%. Trong trường hợp này, việc thêm dữ liệu
- (Chúng tôi sẽ giải thích trong chương sau.) --> Lý do sẽ được giải thích trong chương sau. Cho nó hợp với văn cảnh hơn vì xuyên xuốt bài này chỉ có một tác giả. Mà **_we_** dịch là chúng ta thì hơi kỳ.

2019-12-04 08:30 UTC, ngcthuong commented on chapters/ch20.md
- thì vấn đề trước tiên cần giải quyết là cải thiện chất lượng thuật toán ~~của bạn~~ trên tập huấn luyện.

2019-12-04 08:30 UTC, ngcthuong commented on chapters/ch20.md
- ~~Hiệu quả~~ **_Chất lượng_** trên tập phát triển/kiểm tra thường thấp hơn ~~chất lượng~~ trên tập huấn luyện.

2019-12-04 08:30 UTC, ngcthuong commented on chapters/ch20.md
- Thêm dấu phẩy sau "bởi vậy," thêm "thì", "thể nào" 
> Bởi vậy, nếu bạn đang có độ chính xác 85% trên các mẫu mà thuật toán từng thấy, **_thì_** không ~~có cách nào~~ **_thể nào_** để đạt được độ chính xác 95% cho các mẫu mà thuật toán chưa thấy bao giờ.

2019-12-04 08:30 UTC, ngcthuong commented on chapters/ch20.md
> +* Thứ hai, chất lượng của thuật toán trên tập phát triển (hoặc kiểm tra) kém hơn bao nhiêu so với trên tập huấn luyện. Trong ví dụ này, thuật toán làm việc kém hơn 1% trên tập phát triển so với tập h
- Câu dưới đây dọc nghe hơi ngang, vì cả câu dường như chỉ là một cụm danh từ. Ở đây có thể thêm từ "kiểm tra" hoặc "Tùy thuộc". Để ám chỉ tùy điều kiện khác biệt về chất lượng mà có những phương án xử lý tương ứng. 

> Thứ hai, **_kiểm tra/tùy thuộc_** chất lượng của thuật toán trên tập phát triển (hoặc kiểm tra) kém hơn bao nhiêu so với trên tập huấn luyện.

2019-12-04 08:30 UTC, ngcthuong commented on chapters/ch20.md
> +Một số thay đổi trong thuật toán học có thể giải quyết thành phần thứ nhất của lỗi -- **độ chệch** -- và cải thiện chất lượng của nó trên tập huấn luyện. Một số thay đổi giải quyết thành phần thứ hai
- Mình nghĩ câu " improve its performance on the training set." dịch còn có khả năng hiểu nhầm do từ "it". Từ it's performance ở đây là gì? có thể là "giảm độ chệch " hoặc hiểu sang chất lượng toàn bộ hệ thống.  Bạn cân nhắc lại câu này nhé !

- Gợi ý dịch câu cuối
> Việc nắm được thành phần nào trong hai thành phần lỗi trên là đáng giải quyết hơn sẽ rất hữu ích để trong việc chọn ra những thay đổi tiềm năng nhất.

2019-12-04 08:30 UTC, ngcthuong commented on chapters/ch20.md
>  ----------------
- bỏ từ "một" 
> Phát triển ~~một~~ trực giác tốt về Độ chệch và Phương sai sẽ giúp ~~bạn~~ chọn những thay đổi hữu hiệu cho thuật toán.

2019-12-04 08:30 UTC, ngcthuong commented on chapters/ch20.md
> +[6] Ngành thống kê có những định nghĩa chính thống hơn cho độ chệch và phương sai mà ở đây chúng ta không cần lưu tâm. Đại khái, độ chệch là tỉ lệ lỗi của thuật toán của bạn trên tập huấn luyện khi t
- formal dịch là "chính thống" mình nghe vẫn chưa xuôi xuôi lắm. 
- Đại khái, độ chệch là tỉ lệ lỗi của thuật toán ~~của bạn~~ trên tập huấn luyện khi tập này rất lớn.

2019-12-04 08:30 UTC, ngcthuong commented on chapters/ch20.md
> +[6] Ngành thống kê có những định nghĩa chính thống hơn cho độ chệch và phương sai mà ở đây chúng ta không cần lưu tâm. Đại khái, độ chệch là tỉ lệ lỗi của thuật toán của bạn trên tập huấn luyện khi t
- Từ "mean squared error" thường được dịch là "sai số toàn phương trung bình". Từ này cần được đặt vào glossary vì nó là từ khóa riêng. 
- bỏ dấu phẩy ", và"
>  và chứng minh được rằng Tổng Lỗi = Độ Chệch + Phương Sai.

2019-12-04 08:30 UTC, ngcthuong commented on chapters/ch20.md
> +[6] Ngành thống kê có những định nghĩa chính thống hơn cho độ chệch và phương sai mà ở đây chúng ta không cần lưu tâm. Đại khái, độ chệch là tỉ lệ lỗi của thuật toán của bạn trên tập huấn luyện khi t
- Thêm từ "thì", trình bày
> Nhưng với mục đích xác định làm thế nào để tạo sự tiến triển trong một bài toán học máy, **_thì_** định nghĩa ít chính thống hơn của độ chệch và phương sai như **_trình bày_** ở đây là đã đủ.

2019-12-04 08:30 UTC, ngcthuong commented on chapters/ch20.md
> +[7] Cũng có một vài phương pháp có thể đồng thời giảm độ chệch và phương sai bằng cách tạo sự thay đổi lớn trong kiến trúc hệ thống. Tuy nhiên, những phương pháp này có xu hướng khó phát hiện và triể
- Gợi ý dịch 
> phương sai bằng ~~cách tạo sự~~ **_các_** thay đổi lớn trong kiến trúc hệ thống.

2019-12-04 08:30 UTC, ngcthuong commented on chapters/ch21.md
> +Nó gặp phải vấn đề gì? Áp dụng định nghĩa từ những chương trước, chúng ta ước tính độ chệch là 1% và phương sai là 10% (=11%-1%). Do đó, nó có **phương sai cao**. Bộ phân loại có lỗi huấn luyện rất t
- Không nên dùng từ "Nó" ở đây vì rất tối nghĩa. Gợi ý
> Vậy vấn đề gặp phải là gì? 
- thêm từ "các" 
> Áp dụng **_các_** định nghĩa từ những chương trước,
- Tương tự như trên, không nên dùng từ "nó"
> Do đó, ~~nó~~ vấn đề gặp phải là ~~có~~ thuật toán có **phương sai cao**.

2019-12-04 08:30 UTC, ngcthuong commented on chapters/ch21.md
> +Nó gặp phải vấn đề gì? Áp dụng định nghĩa từ những chương trước, chúng ta ước tính độ chệch là 1% và phương sai là 10% (=11%-1%). Do đó, nó có **phương sai cao**. Bộ phân loại có lỗi huấn luyện rất t
- Gợi ý dịch
> **_Tuy_** bộ phân loại có lỗi huấn luyện rất thấp, nhưng ~~nó~~ lại không khái quát hoá được cho tập phát triển.

2019-12-04 08:30 UTC, ngcthuong commented on chapters/ch21.md
> +Nó gặp phải vấn đề gì? Áp dụng định nghĩa từ những chương trước, chúng ta ước tính độ chệch là 1% và phương sai là 10% (=11%-1%). Do đó, nó có **phương sai cao**. Bộ phân loại có lỗi huấn luyện rất t
- Dùng từ cho rõ nghĩa hơn
> ~~Đây~~ **_Vấn đề này_** cũng được gọi là **overfitting**.

2019-12-04 08:30 UTC, ngcthuong commented on chapters/ch21.md
> +Bây giờ hãy xem xét trường hợp này:
- Trường hợp sau

2019-12-04 08:30 UTC, ngcthuong commented on chapters/ch21.md
> +Chúng ta ước tính độ chệch là 15% và phương sai là 1%. Bộ phân loại này khớp kém với tập huấn luyện với 15% tỉ lệ lỗi, nhưng tỉ lệ lỗi ở tập phát triển chỉ cao hơn một chút so với tập huấn luyện. Do
- từ "nhưng" dùng không có dấu phẩy đi trước trong tiếng Việt.

2019-12-04 08:30 UTC, ngcthuong commented on chapters/ch21.md
>  Bây giờ hãy xem xét điều này:
- Điều này --> trường hợp sau

2019-12-04 08:30 UTC, ngcthuong commented on chapters/ch21.md
- mình vẫn cho rằng tiếng Việt không có dấu phẩy trước từ "và", nếu có dấu phẩy thì bỏ từ "và"
- performance dịch là "chất lượng" chứ không phải hiệu suất.

2019-12-04 08:30 UTC, ngcthuong commented on chapters/ch21.md
- Gợi ý 
> vì bộ phân loại ~~đồng thời~~ bị **_cả_** overfitting ~~và~~ **_lẫn_** underfitting.

2019-12-04 08:30 UTC, ngcthuong commented on chapters/ch21.md
> +Bộ phân loại này đang hoạt động tốt, vì nó có độ chệch thấp và phương sai thấp. Chúc mừng bạn đã đạt được một hiệu suất tuyệt vời!
- không có dấu phẩy trước từ "vì"

2019-12-04 08:30 UTC, ngcthuong commented on chapters/ch22.md
> +Một số bài toán khác thì khó hơn. Ví dụ như chúng ta xây dựng một hệ thống nhận dạng giọng nói và nhận ra rằng 14% các clip âm thanh có quá nhiều nhiễu nền hoặc khó hiểu tới mức ngay cả con người cũn
- từ clip dịch ra là "đoạn"

2019-12-04 08:30 UTC, ngcthuong commented on chapters/ch22.md
> +Một số bài toán khác thì khó hơn. Ví dụ như chúng ta xây dựng một hệ thống nhận dạng giọng nói và nhận ra rằng 14% các clip âm thanh có quá nhiều nhiễu nền hoặc khó hiểu tới mức ngay cả con người cũn
- gợi ý
> khó hiểu tới mức ngay cả con người cũng không thể **_nghe_** ~~nhận~~ ra ~~những gì được nói~~.

2019-12-04 08:30 UTC, ngcthuong commented on chapters/ch22.md
- Chất lượng trên tập huấn luyện **_hiện_** đã gần với tỉ lệ lỗi tối ưu là 14%.

2019-12-04 08:30 UTC, ngcthuong commented on chapters/ch22.md
dấu ";" được dùng trong đoạn văn gốc bị chuyển sang dấu ","

2019-12-04 08:30 UTC, ngcthuong commented on chapters/ch22.md
> +Ví dụ này tương tự như ví dụ thứ ba trong chương trước, cũng có lỗi huấn luyện là 15% và lỗi phát triển là 30%. Nếu tỉ lệ lỗi tối ưu là xấp xỉ 0%, thì 15% lỗi huấn luyện để lại nhiều chỗ trống để cải
- Ví dụ này tương tự như ví dụ thứ ba trong chương trước ~~,~~ **_khi_** cũng có lỗi huấn luyện là 15% và lỗi phát triển là 30%.

2019-12-04 08:30 UTC, ngcthuong commented on chapters/ch22.md
> +Ví dụ này tương tự như ví dụ thứ ba trong chương trước, cũng có lỗi huấn luyện là 15% và lỗi phát triển là 30%. Nếu tỉ lệ lỗi tối ưu là xấp xỉ 0%, thì 15% lỗi huấn luyện để lại nhiều chỗ trống để cải
- Câu gốc dịch nghe hơi ngang dù rất đúng nghĩa. Mình gợi ý chỉnh lại là 
> Nếu tỉ lệ lỗi tối ưu là xấp xỉ 0%, thì mức 15% lỗi huấn luyện sẽ để lại nhiều khả năng cải thiện hơn.

2019-12-04 08:30 UTC, ngcthuong commented on chapters/ch22.md
> +Ví dụ này tương tự như ví dụ thứ ba trong chương trước, cũng có lỗi huấn luyện là 15% và lỗi phát triển là 30%. Nếu tỉ lệ lỗi tối ưu là xấp xỉ 0%, thì 15% lỗi huấn luyện để lại nhiều chỗ trống để cải
- thêm từ nhiều cho hợp nghĩa "fruitful" 
> Điều này gợi ý ~~cho chúng ra~~ rằng những thay đổi làm giảm độ chệch có thể mang lại **_nhiều_** kết quả.

2019-12-04 08:30 UTC, ngcthuong commented on chapters/ch22.md
> +Ví dụ này tương tự như ví dụ thứ ba trong chương trước, cũng có lỗi huấn luyện là 15% và lỗi phát triển là 30%. Nếu tỉ lệ lỗi tối ưu là xấp xỉ 0%, thì 15% lỗi huấn luyện để lại nhiều chỗ trống để cải
> Nhưng nếu tỉ lệ lỗi tối ưu là 14%, thì chất lượng tương tự trên tập huấn luyện ~~sẽ cho chúng ta biết rằng~~ **_cho thấy_** có rất ít ~~chỗ~~ **_cơ hội_** để cải thiện độ chệch của bộ phân loại.

2019-12-04 08:30 UTC, ngcthuong commented on chapters/ch22.md
>  Với các bài toán trong đó tỉ lệ lỗi tối ưu khác xa 0%, đây là phân tích chi tiết hơn về lỗi của một thuật toán. Tiếp tục với ví dụ nhận dạng giọng nói của chúng ta ở trên, lỗi tổng cộng trên tập phát
- Khác xa dịch là "lớn hơn nhiều", sửa lại vế 2 của câu 1 cho đúng nghĩa. 
> Với các bài toán trong đó tỉ lệ lỗi tối ưu ~~khác xa~~ **_lớn hơn nhiều mức_** 0%, thì có một cách phân tích chi tiết hơn về lỗi của thuật toán.

2019-12-04 08:30 UTC, ngcthuong commented on chapters/ch22.md
>  Với các bài toán trong đó tỉ lệ lỗi tối ưu khác xa 0%, đây là phân tích chi tiết hơn về lỗi của một thuật toán. Tiếp tục với ví dụ nhận dạng giọng nói của chúng ta ở trên, lỗi tổng cộng trên tập phát
- Bỏ từ thừa 
> Tiếp tục với ví dụ nhận dạng giọng nói ~~của chúng ta~~ ở trên, lỗi tổng cộng trên tập phát triển là 30% ~~và nó~~ có thể được chia nhỏ như sau (~~một~~ phân tích tương tự có thể ~~được~~ áp dụng cho lỗi trên tập kiểm tra):

2019-12-04 08:30 UTC, ngcthuong commented on chapters/ch22.md
> +* **Tỉ lệ lỗi tối ưu ("độ chệch không tránh được")**: 14%. Giả sử chúng ra quyết định rằng, ngay cả khi dùng hệ thống nhận dạng giọng nói tốt nhất trên thế giới, chúng ta vẫn phải chịu 14% lỗi. Chúng
- thêm từ "thì". Đôi lúc dùng "ta" thanh cho "chúng ta" nghe thuận hơn. 
> ngay cả khi dùng hệ thống nhận dạng giọng nói tốt nhất trên thế giới, thì ~~chúng~~ ta vẫn phải chịu 14% lỗi.

2019-12-04 08:30 UTC, ngcthuong commented on chapters/ch22.md
> +* **Tỉ lệ lỗi tối ưu ("độ chệch không tránh được")**: 14%. Giả sử chúng ra quyết định rằng, ngay cả khi dùng hệ thống nhận dạng giọng nói tốt nhất trên thế giới, chúng ta vẫn phải chịu 14% lỗi. Chúng
> ~~Chúng~~ Ta có thể coi lỗi đó là phần "không tránh được" của độ chệch của ~~một~~ thuật toán học máy.

2019-12-04 08:30 UTC, ngcthuong commented on chapters/ch22.md
> +* **Độ chệch tránh được**: 1%. Hiệu giữa lỗi huấn luyện và lỗi tối ưu. [8]
Chap trước dịch là "tỉ lệ lỗi huấn luyện" mà chap này lại để là "lỗi huấn luyện".

2019-12-04 08:30 UTC, ngcthuong commented on chapters/ch22.md
> +Để kết nối điều này với những định nghĩa trước kia, Độ chệch tránh được và Độ chệch liên hệ với nhau như sau: [9]
- Dùng từ "liên hệ" hay hơn là "kết nối" 
> ~~Để kết nối điều này~~ Từ những định nghĩa trước, thì mối liên hệ giữa Độ chệch và Độ chệch tránh được là: [9]

2019-12-04 08:30 UTC, ngcthuong commented on chapters/ch22.md
> +"Độ chệch tránh được" phản ánh thuật toán của bạn hoạt động kém bao nhiêu so với "bộ phân loại tối ưu".
> "Độ chệch tránh được" phản ánh **_mức hoạt động kém_** của thuật toán của bạn ~~kém bao nhiêu~~ so với "bộ phân loại tối ưu".

2019-12-04 08:30 UTC, ngcthuong commented on chapters/ch22.md
> +Khái niệm phương sai vẫn giữ nguyên như trước. Theo lý thuyết, chúng ta luôn có thể giảm phương sai về gần 0 bằng cách huấn luyện trên một tập huấn luyện cực lớn. Do đó, tất cả phương sai là "tránh đ
- 0 --> không

2019-12-04 08:30 UTC, ngcthuong commented on chapters/ch22.md
> +Khái niệm phương sai vẫn giữ nguyên như trước. Theo lý thuyết, chúng ta luôn có thể giảm phương sai về gần 0 bằng cách huấn luyện trên một tập huấn luyện cực lớn. Do đó, tất cả phương sai là "tránh đ
- bỏ dấu phẩy trước từ 'và'

2019-12-04 08:30 UTC, ngcthuong commented on chapters/ch22.md
- chúng ta --> ta

2019-12-04 08:30 UTC, ngcthuong commented on chapters/ch22.md
> +Trong khi ở chương trước chúng ta gọi đây là một bộ phân loại có độ chệch cao, bây giờ chúng ta nói rằng lỗi từ độ chệch tránh được là 1% và lỗi từ phương sai là khoảng 1%. Do đó, thuật toán của chún
- Mình thấy từ "khoảng trống để cải thiện" nghe hơi giống tiêng Anh hơn là tiếng Việt.

2019-12-04 08:30 UTC, ngcthuong commented on chapters/ch22.md
> +Làm sao chúng ta biết được tỉ lệ lỗi tối ưu? Với những việc mà con người làm tốt, như nhận dạng ảnh hay phiên âm clip, bạn có thể nhờ ai đó gán nhãn sau đó đo độ chính xác của những nhãn này với tập
- clip dịch là đoạn 
- transcription dịch là "bản ghi thoại" 
- bỏ bớt từ "của bạn" 
- thêm dấu phẩy trước từ "thì" ở câu cuối. 

Mà sao mình thấy mấy từ này chưa được update trong Glossary nhỉ @tiepvupsu ?

2019-12-04 08:30 UTC, ngcthuong commented on chapters/ch22.md
> +Trong một vài chương trước, bạn đã học cách ước tính phương sai và độ chệch tránh được/không tránh được bằng cách xem xét tỉ lệ lỗi huấn luyện và phát triển. Chương tiếp theo sẽ thảo luận về cách bạn
- Trong một vài chương trước,  --> một vài chương gần đây 
- "ước tính" --> tính 
- "xem xét tỉ lệ lỗi huấn luyện và phát triển. " --> xem xét tỉ lệ lỗi huấn luyện và tỉ lệ lỗi phát triển.

2019-12-04 08:30 UTC, ngcthuong commented on chapters/ch22.md
> +Trong một vài chương trước, bạn đã học cách ước tính phương sai và độ chệch tránh được/không tránh được bằng cách xem xét tỉ lệ lỗi huấn luyện và phát triển. Chương tiếp theo sẽ thảo luận về cách bạn
- Hãy đọc tiếp ---> Hồi sau sẽ rõ.

2019-12-04 08:30 UTC, ngcthuong commented on chapters/ch22.md
> +[8] Nếu con số này là âm, bạn đang làm tốt hơn ở trên tập huấn luyện so với tỉ lệ lỗi tối ưu. Điều này có nghĩa là bạn đang overfitting tập huấn luyện và thuật toán đã ghi nhớ quá mức tập huấn luyện.
- Cấu trúc nếu thì --> thêm "thì"
> Nếu con số này là âm, **_thì_** bạn đang làm tốt ~~hơn ở~~ trên tập huấn luyện **_hơn_** so với tỉ lệ lỗi tối ưu. 
- Câu cuối để bản gốc đúng nghĩa hơn.

2019-12-04 08:30 UTC, ngcthuong commented on chapters/ch23.md
> +* Nếu bạn có độ chệch tránh được cao, hãy tăng kích thước mô hình của bạn (ví dụ: tăng kích thước của mạng nơ-ron bằng cách thêm các tầng/nơ-ron)
- có thể bỏ từ "của bạn" và "bạn"

2019-12-04 08:40 UTC, rootonchair commented
> Có sự không đồng nhất về dịch từ "training error" tỉ lệ lỗi huấn luyện (khi có "tỉ lệ", khi không).

Mình có kiểm tra và sửa những chỗ không đồng nhất như vậy. Có thể từ "tỉ lệ" bạn gặp là từ "training error rate"

Còn phần comment thì ... để mình đọc dần :sweat_smile: . Thank bạn

2019-12-04 09:05 UTC, aivivn requested changes
Anh yêu cầu sửa ở tài khoản này phòng khi ai đó lỡ ấn nhầm nút merge :D.

2019-12-05 15:30 UTC, rootonchair commented on chapters/ch20.md
> +Một số thay đổi trong thuật toán học có thể giải quyết thành phần thứ nhất của lỗi -- **độ chệch** -- và cải thiện chất lượng của nó trên tập huấn luyện. Một số thay đổi giải quyết thành phần thứ hai
Theo em thì " improve its performance on the training set." ý nói giảm độ chệch của thuật toán trên tập huấn luyện. Em không biết nếu để nguyên thì có nguy cơ bị hiểu nhầm không?

2019-12-05 15:33 UTC, rootonchair commented on chapters/ch20.md
>  ----------------
Em sẽ giữ lại từ "bạn". Một phần là vì đọc trôi chảy hơn.

2019-12-05 15:54 UTC, tiepvupsu commented on chapters/ch20.md
> +Mặc dù có thêm dữ liệu không làm tổn hại đến hiệu quả, thật không may, điều này không phải lúc nào cũng mang lại hiệu quả nhiều như mong đợi. Việc thu thập thêm dữ liệu có thể trở nên lãng phí thời g
Ok đó em.

2019-12-05 15:59 UTC, tiepvupsu commented on chapters/ch20.md
> +Có hai nguồn chính dẫn đến lỗi trong học máy: độ chệch và phương sai. Hiểu được chúng sẽ giúp bạn quyết định liệu rằng có đáng bỏ thời gian ra để thêm dữ liệu, cũng như áp dụng các kỹ thuật khác để c
@ngcthuong dùng chức năng suggestion đi cậu. Review và commit đều nhanh:
![img](https://user-images.githubusercontent.com/19977/58752991-f39d0880-846c-11e9-8c03-c7aded86ee9b.png)

2019-12-05 16:01 UTC, tiepvupsu commented on chapters/ch22.md
> +Làm sao chúng ta biết được tỉ lệ lỗi tối ưu? Với những việc mà con người làm tốt, như nhận dạng ảnh hay phiên âm clip, bạn có thể nhờ ai đó gán nhãn sau đó đo độ chính xác của những nhãn này với tập
@ngcthuong có lẽ bị sót. Tạo luôn PR đi cậu.

2019-12-05 16:08 UTC, tiepvupsu commented on chapters/ch20.md
> +Mặc dù có thêm dữ liệu không làm tổn hại đến hiệu quả, thật không may điều này không phải lúc nào cũng mang lại hiệu quả nhiều như bạn mong đợi. Việc thu thập thêm dữ liệu có thể trở nên lãng phí thờ
@ngcthuong dùng chức năng suggestion đi cậu.

2019-12-06 02:48 UTC, rootonchair commented on chapters/ch21.md
Phần gợi ý em nghĩ không ảnh hưởng nhiều nên em sẽ giữ nguyên

2019-12-06 03:19 UTC, rootonchair commented on chapters/ch22.md
> +"Độ chệch tránh được" phản ánh thuật toán của bạn hoạt động kém bao nhiêu so với "bộ phân loại tối ưu".
Em thấy gợi ý này không mượt như bản gốc nên sẽ giữ nguyên

2019-12-06 03:32 UTC, rootonchair commented on chapters/ch22.md
> +Làm sao chúng ta biết được tỉ lệ lỗi tối ưu? Với những việc mà con người làm tốt, như nhận dạng ảnh hay phiên âm clip, bạn có thể nhờ ai đó gán nhãn sau đó đo độ chính xác của những nhãn này với tập
@tiepvupsu có "transcribe" là động từ nên em dịch là "phiên thoại" nhé

2019-12-06 03:58 UTC, ngcthuong reviewed
Bản dịch khá hoàn thiện. Mình chỉ góp ý thêm một vài lỗi nhỏ và cần update từ khóa "overfitting" như thảo luận ở trên.

2019-12-06 03:58 UTC, ngcthuong commented on chapters/ch22.md
> +[9] Những định nghĩa này được chọn để truyền đạt cái nhìn sâu sắc về cách cải thiện thuật toán học máy của bạn. Những định nghĩa này khác với cách các nhà thống kê định nghĩa Độ chệch và Phương sai.
```suggestion
[9] Những định nghĩa này được chọn để truyền đạt cái nhìn sâu sắc về cách cải thiện thuật toán học máy của bạn. Những định nghĩa này khác với cách các nhà thống kê định nghĩa Độ chệch và Phương sai. Về mặt kỹ thuật, những gì tôi định nghĩa là "Độ chệch" nên được gọi là "Lỗi chúng ta quy cho độ chệch" và "Độ chệch tránh được" nên là "Lỗi chúng ta quy cho độ chệch của thuật toán học mà lớn hơn tỉ lệ lỗi tối ưu" .
```

2019-12-06 03:58 UTC, ngcthuong commented on chapters/ch20.md
> +Mặc dù có thêm dữ liệu không gây ảnh hưởng xấu, thật không may, điều này không phải lúc nào cũng mang lại hiệu quả nhiều như mong đợi. Việc thu thập thêm dữ liệu có thể trở nên lãng phí thời gian. Vậ
```suggestion
Mặc dù có thêm dữ liệu không gây ảnh hưởng xấu, thì thật không may, điều này không phải lúc nào cũng mang lại hiệu quả nhiều như mong đợi. Việc thu thập thêm dữ liệu có thể trở nên lãng phí thời gian. Vậy làm thế nào để quyết định khi nào nên hoặc không nên thêm dữ liệu?
```

2019-12-06 03:58 UTC, ngcthuong commented on chapters/ch20.md
> +Có hai nguồn chính dẫn đến lỗi trong học máy: độ chệch và phương sai. Hiểu được chúng sẽ giúp bạn quyết định liệu việc thêm dữ liệu hay áp dụng các kỹ thuật khác để cải thiện chất lượng của mô hình c
```suggestion
Có hai nguồn lỗi chính trong học máy: độ chệch và phương sai. Hiểu được chúng sẽ giúp bạn quyết định liệu việc thêm dữ liệu hay áp dụng các kỹ thuật khác để cải thiện chất lượng của mô hình có đáng để bỏ thời gian ra không.
```

2019-12-06 03:58 UTC, ngcthuong commented on chapters/ch20.md
tạm nghĩ --> tạm coi

2019-12-06 03:58 UTC, ngcthuong commented on chapters/ch22.md
> +"Độ chệch tránh được" phản ánh thuật toán của bạn hoạt động kém bao nhiêu so với "bộ phân loại tối ưu".
```suggestion
"Độ chệch tránh được" phản ánh thuật toán của bạn hoạt động kém hơn bao nhiêu so với "bộ phân loại tối ưu".
```

2019-12-06 03:58 UTC, ngcthuong commented on chapters/ch22.md
> +Từ những ví dụ này chúng ta thấy rằng tỉ lệ lỗi tối ưu rất hữu ích cho việc định hướng các bước tiếp theo. Trong thống kê, tỉ lệ lỗi tối ưu còn được gọi là **tỉ lệ lỗi Bayes**, hay tỉ lệ Bayes.
```suggestion
Từ những ví dụ này chúng ta thấy rằng tỉ lệ lỗi tối ưu rất hữu ích cho việc định hướng các bước tiếp theo. Trong thống kê, tỉ lệ lỗi tối ưu còn được gọi là **tỉ lệ lỗi Bayes** hay tỉ lệ Bayes.
```

2019-12-06 03:58 UTC, ngcthuong commented on chapters/ch23.md
>  * Nếu bạn có phương sai cao, hãy thêm dữ liệu vào tập huấn luyện của bạn.
```suggestion
* Nếu bạn có phương sai cao, hãy thêm dữ liệu vào tập huấn luyện.
```

2019-12-06 03:58 UTC, ngcthuong commented on chapters/ch23.md
> +Nếu bạn có thể tăng kích thước của mạng nơ-ron và dữ liệu huấn luyện lên vô hạn thì bạn sẽ có khả năng xử lý rất tốt trên nhiều bài toán học máy.
```suggestion
Nếu bạn có thể tăng kích thước của mạng nơ-ron và dữ liệu huấn luyện lên vô hạn, thì bạn sẽ có khả năng xử lý rất tốt trên nhiều bài toán học máy.
```

2019-12-06 03:58 UTC, ngcthuong commented on chapters/ch23.md
> +Trong thực tế, việc tăng kích thước của mô hình cuối cùng sẽ khiến bạn gặp phải các vấn đề về tính toán bởi vì việc huấn luyện các mô hình cực lớn là rất chậm. Bạn có thể cũng sẽ làm cạn kiệt khả năn
```suggestion
Trong thực tế, việc tăng kích thước của mô hình cuối cùng sẽ khiến bạn gặp phải các vấn đề về tính toán bởi vì việc huấn luyện các mô hình cực lớn là rất chậm. Bạn có thể cũng sẽ làm cạn kiệt khả năng có được nhiều dữ liệu huấn luyện hơn. (Ngay cả trên mạng internet cũng chỉ có một số lượng hữu hạn hình ảnh mèo!)
```

2019-12-06 03:58 UTC, ngcthuong commented on chapters/ch23.md
> +Những kiến trúc mô hình khác nhau -- ví dụ, các kiến trúc mạng nơ-ron khác nhau -- sẽ có các mức độ chệch/phương sai khác nhau cho vấn đề của bạn. Những nghiên cứu gần đây về học sâu đã phát triển nh
```suggestion
Những kiến trúc mô hình khác nhau -- ví dụ, các kiến trúc mạng nơ-ron khác nhau -- sẽ có các mức độ chệch/phương sai khác nhau cho vấn đề của bạn. Những nghiên cứu gần đây về học sâu đã phát triển nhiều kiến trúc mô hình đột phá. Vì vậy, nếu bạn đang sử dụng mạng nơ-ron, những tài liệu học thuật có thể là một nguồn cảm hứng tuyệt vời. Ngoài ra còn có rất nhiều cài đặt mã nguồn mở tuyệt vời trên GitHub. Nhưng kết quả của việc thử nghiệm các kiến trúc mới khó dự đoán hơn so với công thức đơn giản của việc tăng kích thước mô hình và thêm dữ liệu.
```

2019-12-06 04:54 UTC, tiepvupsu commented on chapters/ch22.md
> +Làm sao chúng ta biết được tỉ lệ lỗi tối ưu? Với những việc mà con người làm tốt, như nhận dạng ảnh hay phiên âm clip, bạn có thể nhờ ai đó gán nhãn sau đó đo độ chính xác của những nhãn này với tập
Ok em.

Nhanh chóng merge PR này nhé @rootonchair, @ngcthuong.

2019-12-06 05:31 UTC, ngcthuong commented on chapters/ch20.md
> +Có hai nguồn chính dẫn đến lỗi trong học máy: độ chệch và phương sai. Hiểu được chúng sẽ giúp bạn quyết định liệu rằng có đáng bỏ thời gian ra để thêm dữ liệu, cũng như áp dụng các kỹ thuật khác để c
Uhm, dùng cái này tiện hơn hẳn

2019-12-06 05:32 UTC, ngcthuong commented on chapters/ch22.md
> +Làm sao chúng ta biết được tỉ lệ lỗi tối ưu? Với những việc mà con người làm tốt, như nhận dạng ảnh hay phiên âm clip, bạn có thể nhờ ai đó gán nhãn sau đó đo độ chính xác của những nhãn này với tập
mình thấy khá ok rồi. Em @rootonchair  check nốt mấy comment nhỏ của mình là oK đó.

2019-12-06 08:38 UTC, rootonchair commented on chapters/ch20.md
> +* Thứ hai, chất lượng của thuật toán trên tập phát triển (hoặc kiểm tra) kém hơn bao nhiêu so với trên tập huấn luyện. Trong ví dụ này, thuật toán làm việc kém hơn 1% trên tập phát triển so với tập h
Em sẽ giữ nguyên vì trong phần này tác giả đang liệt kê các thành phần lỗi.

2019-12-08 01:31 UTC, ngcthuong commented
Mình tưởng là thống nhất cập nhật từ khóa "overfitting" rồi chứ nhỉ?

2019-12-08 10:55 UTC, rootonchair commented
Theo anh Tiệp thì nên để lại rồi sửa đồng loạt luôn vì các chương khác cũng có từ này

2019-12-08 16:07 UTC, ngcthuong approved these changes
Vậy thì ổn rồi. mình sẽ approve bản dịch này. Cảm ơn em.

2019-12-08 18:19 UTC, aivivn approved these changes

2019-12-08 18:19 UTC, aivivn commented
> Theo anh Tiệp thì nên để lại rồi sửa đồng loạt luôn vì các chương khác cũng có từ này

@rootonchair em có thể giúp sửa đồng loạt các chương được không?

2019-12-08 18:19 UTC, merged

2019-12-09 02:02 UTC, rootonchair commented
@aivivn Anh có thể tạo issue và nêu yêu cầu. Em sẽ nhận