Tạo thư mục ảnh
aivivn/Machine-Learning-Yearning-Vietnamese-Translation pull request #8
Opened 2019-10-17 07:47 UTC by aivivn

Tạo thư mục image, readme, và link

2019-10-17 07:49 UTC, aivivn commented
@ngcthuong cần rebase vào master vì file `README.md` đang bị conflict.

2019-10-17 07:55 UTC, aivivn commented on README.md
> +File ảnh của tất cả các chương đều để chung tại thư mục /img, với cách lưu tên file [tại đây](img/readme.md)
* @ngcthuong cậu đặt câu này trong một header mới `## Thư mục ảnh`.
* Phần /img nên đặt trong cặp '`' để nó hiển thị như code.
* Thiếu dấu chấm cuối câu.
* 'đều để chung' -> 'để chung'. Chữ 'chung' và chữ 'đều' bị lặp.

2019-10-17 07:55 UTC, aivivn commented on img/readme.md
> +- Ảnh để định dạng .png hoặc .jpg ở chất lượng cao nhất.
* `.png` và `.jpg` đặt trong cặp dấu '`'.
* Cậu cũng nên hướng dẫn là ảnh có thể chụp màn hình từ file pdf.

2019-10-17 07:55 UTC, aivivn commented on img/readme.md
> +- Đặt tên ảnh dựa trên chương, và thứ tự suất hiện. Ví dụ ảnh thứ 3 ở chương 1 sẽ có tên là C01_03.png
* Bỏ dấu phẩy giữa 'chương' và 'và'.
* 'suất hiện' -> 'xuất hiện'.
* `C01_03.png` đặt trong cặp dấu '`'

2019-10-17 07:55 UTC, aivivn commented on img/readme.md
> +
Hạn chế các trailing blank lines.

2019-10-17 07:58 UTC, tiepvupsu commented on img/readme.md
> +- Ảnh để định dạng .png hoặc .jpg ở chất lượng cao nhất.
Thống nhất dùng dấu `*` để tạo bullet thay vì dấu gạch `-` nhé.

2019-10-17 07:59 UTC, tiepvupsu requested changes
Cậu sửa hết mấy cái mà @aivivn yêu cầu nhé.

2019-10-17 08:03 UTC, aivivn commented
Có môt lưu ý nữa là nên đặt tên branch có nghĩa hơn. Ví dụ, `create_img_folder` thì rõ nghĩa hơn là `tag`.

2019-10-18 07:17 UTC, tiepvupsu commented
Để resolve conflict thì cậu phải rebase:
```
git checkout master
git pull
git checkout task
git rebase master
```
Sau đó nó sẽ dừng ở chỗ có CONFLICT, rồi cậu mở file conflict ra để resolve. Resolve xong hết rồi thì update lại:
```
git push -u -f origin HEAD
```

2019-10-19 04:43 UTC, aivivn commented
Chuyển sang #30

2019-10-19 04:43 UTC, closed without merging