update glossary chap 1 -14
aivivn/Machine-Learning-Yearning-Vietnamese-Translation pull request #81
Opened 2019-10-20 03:16 UTC by ngcthuong

Bản update đầu tiên gồm
- thống kê các từ khóa từ chap 1 - 14
- dịch tạm mộ số từ khóa

Cần nhiều đống góp để hoàn thiện và chuẩn hóa

2019-10-20 03:28 UTC, tiepvupsu requested changes

2019-10-20 03:28 UTC, tiepvupsu commented on glossary.md
> +| benchmark                         | bảng so sánh                        |
Từ này dễ gây tranh cãi, cậu tạm bỏ ra khỏi PR này đã.

2019-10-20 03:28 UTC, tiepvupsu commented on glossary.md
> +| constrain                         | giới hạn                            |
constraint = ràng  buộc.

2019-10-20 03:28 UTC, tiepvupsu commented on glossary.md
> +| deep learning                     | học sâu                             |
machine learning mình giữ nguyên nên deep learning cũng giữ nguyên.

2019-10-20 03:28 UTC, tiepvupsu commented on glossary.md
> +| distribution                      | phân bô                             |
phân phối

2019-10-20 03:28 UTC, tiepvupsu commented on glossary.md
> +| hand-engineering                  | tự tạo                              |
từ này dễ gây tranh cãi.

2019-10-20 03:28 UTC, tiepvupsu commented on glossary.md
> +| learning curve                    | đường học                           |
từ này cũng dễ gây tranh cãi.

2019-10-20 03:28 UTC, tiepvupsu commented on glossary.md
> +| learning algorithm                | thuật toán học máy                  |
không có chữ 'máy' ở đây.

2019-10-20 03:28 UTC, tiepvupsu commented on glossary.md
> +| negative examples                 | nhãn tiêu cực                       |
chưa chuẩn lắm, tạm bỏ ra.

2019-10-20 03:28 UTC, tiepvupsu commented on glossary.md
> +| optimizing metric                 | phép đo tối ưu                      |
Từ này trong văn cảnh nào thế nhỉ? Có vẻ như nó là cụm động từ, nếu thế cần dịch là 'tối ưu phép đo'.

2019-10-20 03:28 UTC, tiepvupsu commented on glossary.md
> +| satisficing metric                | phép đo thỏa mãn                    |
Cậu cho văn cảnh từ này

2019-10-20 03:28 UTC, tiepvupsu commented on glossary.md
> +| single number evaluation metric   | phép đánh dùng một giá trị duy nhất |
'single-number'

2019-10-20 03:28 UTC, tiepvupsu commented on glossary.md
> +| spam email                        | thư rác                             |
email rác

2019-10-20 03:28 UTC, tiepvupsu commented on glossary.md
> +|                                   |                                     |
thừa dòng.

2019-10-20 03:32 UTC, ngcthuong commented on glossary.md
> +| optimizing metric                 | phép đo tối ưu                      |
cậu xem chap 9 nhé

2019-10-20 03:32 UTC, ngcthuong commented on glossary.md
> +| satisficing metric                | phép đo thỏa mãn                    |
từ khóa chứ không phải động từ

2019-10-20 03:36 UTC, ngcthuong commented on glossary.md
> +| negative examples                 | nhãn tiêu cực                       |
là từ nào thế?

2019-10-20 03:37 UTC, ngcthuong commented on glossary.md
> +| satisficing metric                | phép đo thỏa mãn                    |
satisficing metric cũng ở chap 9

2019-10-20 03:58 UTC, tiepvupsu commented on glossary.md
> +| benchmark                         | bảng so sánh                        |
Cậu bỏ nhầm từ rồi. Accuracy chuẩn, ý tớ là bỏ dịch từ benchmark ra.

2019-10-20 03:58 UTC, tiepvupsu commented on glossary.md
> +| feature                           |                                     |
đặc trưng là chuẩn rồi, giữ lại nhé.

2019-10-20 03:58 UTC, tiepvupsu commented on glossary.md
> +| hand-engineering                  | tự tạo                              |
Tạm bỏ từ 'tự tạo' này đi cậu.

2019-10-20 03:58 UTC, tiepvupsu commented on glossary.md
> +| learning curve                    | đường học                           |
Đừng ấn nút resolve vội. Nếu cậu không đồng ý thì giải thích chứ.

2019-10-20 03:58 UTC, tiepvupsu commented on glossary.md
> +| satisficing metric                | phép đo thỏa mãn                    |
Dịch hơi củ chuối nhỉ, tạm thời bỏ ra đã cậu.

2019-10-20 05:36 UTC, tiepvupsu commented on glossary.md
> +| positive sample                   | nhãn tích cực      |
từ này không có nghĩa là 'tích cực', cậu tạm bỏ đi đã.

2019-10-20 05:36 UTC, tiepvupsu commented on glossary.md
> +| benchmark                         | bảng so sánh       |
cần thảo luận thêm từ này.

2019-10-20 05:36 UTC, tiepvupsu commented on glossary.md
> +| hand-engineering                  | tự tạo             |
cần thảo luận thêm từ này.

2019-10-20 05:36 UTC, tiepvupsu commented on glossary.md
> +| negative examples                 | nhãn tiêu cực      |
cần thảo luận thêm từ này.

2019-10-20 05:36 UTC, tiepvupsu commented on glossary.md
> +| optimizing metric                 | phép đo tối ưu     |
cần thảo luận thêm từ này.

2019-10-20 05:36 UTC, tiepvupsu commented on glossary.md
> +| precision                         |                    |
giữ nguyên 'precision'.

2019-10-20 05:36 UTC, tiepvupsu commented on glossary.md
> +| recall                            |                    |
giữ nguyên recall

2019-10-20 05:36 UTC, tiepvupsu commented on glossary.md
> +| satisficing metric                | phép đo thỏa mãn   |
cần thảo luận thêm từ này.

2019-10-20 05:42 UTC, tiepvupsu approved these changes

2019-10-20 05:42 UTC, merged

2019-10-23 05:20 UTC, skhanhnguyen commented on glossary.md
> +| satisficing metric                | phép đo thỏa mãn                    |
satifsficing metric có thể dịch sát hơn với nghĩa trong ngữ cảnh này, nôm na là "độ đo/phép đo vừa đủ/vừa đạt"

2019-10-23 05:21 UTC, skhanhnguyen commented on glossary.md
> +| benchmark                         | bảng so sánh       |
Wiki tiếng Việt dịch benchmark trong business thành đối chuẩn: https://vi.wikipedia.org/wiki/%C4%90%E1%BB%91i_chu%E1%BA%A9n

2019-10-23 05:23 UTC, skhanhnguyen commented on glossary.md
> +| recall                            |                    |
Recall có được dịch ra tiếng Việt trong văn cảnh chẩn đoán bệnh thành "độ nhạy".
https://vi.wikipedia.org/wiki/%C4%90%E1%BB%99_nh%E1%BA%A1y_v%C3%A0_%C4%91%E1%BB%99_%C4%91%E1%BA%B7c_hi%E1%BB%87u